### ISSUE TITLE
New playground games 

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#104]
```
Train Miner
``` 
```
Chain Cube 2048
``` 
```
My Clone Army
``` 

![IMG_20240806_132957](https://github.com/user-attachments/assets/6ee3729f-07b9-4bc0-9e7f-41128f77e07f)

**Comment by akumanomi1988** [comment]
> ```
> Train Miner
> ```
> 
> ```
> Chain Cube 2048
> ```
> 
> ```
> My Clone Army
> ```
> 
> ![IMG_20240806_132957](https://private-user-images.githubusercontent.com/175958587/355414189-6ee3729f-07b9-4bc0-9e7f-41128f77e07f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDEzOTAsIm5iZiI6MTcyMjk0MTA5MCwicGF0aCI6Ii8xNzU5NTg1ODcvMzU1NDE0MTg5LTZlZTM3MjlmLTA3YjktNGJjMC05ZTdmLTQxMTI4Zjc3ZTA3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMDQ0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMThhMjdhMDIxNGIwMjI5NGEzZTkzNWIzMmEyZDAyYTUyMTY0ZGU2N2FjNWFlMWZjMmRiZGNlNTY2M2EzZjcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aNtc7bImuEprmM053iDSnBf1G5Y-AIG9chnG_znBGp8)

That was so fast! xD

@masterking32 if i receive some airdrop, i will give you a part.

**Comment by WildKiwiFox** [comment]
> That was so fast! xD
> 
> @masterking32 if i receive some airdrop, i will give you a part.

How to download soft for these games?

**Comment by dyonis** [comment]
> That was so fast! xD
> 
> @masterking32 if i receive some airdrop, i will give you a part.

Me too

**Comment by WildKiwiFox** [comment]
> > That was so fast! xD
> > @masterking32 if i receive some airdrop, i will give you a part.
> 
> Me too

 Me too xd

**Comment by Microzibert** [comment]
> That was so fast! xD
> 
> @masterking32 if i receive some airdrop, i will give you a part.

Seriously though, I have four accounts and from each I will give part of the airdrop

**Comment by daigia99xx** [comment]
Me too

**Comment by miladesign** [comment]
found this. hope its help you
```
games = [
  {
    name: "Riding Extreme 3D",
    appToken: "d28721be-fd2d-4b45-869e-9f253b554e50",
    promoId: "43e35910-c168-4634-ad4f-52fd764a843f"
  },
  {
    name: "Chain Cube",
    appToken: "d1690a07-3780-4068-810f-9b5bbf2931b2",
    promoId: "b4170868-cef0-424f-8eb9-be0622e8e8e3"
  },
  {
    name: "My Clone Army",
    appToken: "74ee0b5b-775e-4bee-974f-63e7f4d5bacb",
    promoId: "fe693b26-b342-4159-8808-15e3ff7f8767"
  },
  {
    name: "Train Miner",
    appToken: "82647f43-3f87-402d-88dd-09a90025313f",
    promoId: "c4480ac7-e178-4973-8061-9ed5b2e17954"
  }
]
```

**Comment by supmyhava** [comment]
> games = [
>   {
>     name: "Riding Extreme 3D",
>     appToken: "d28721be-fd2d-4b45-869e-9f253b554e50",
>     promoId: "43e35910-c168-4634-ad4f-52fd764a843f"
>   },
>   {
>     name: "Chain Cube",
>     appToken: "d1690a07-3780-4068-810f-9b5bbf2931b2",
>     promoId: "b4170868-cef0-424f-8eb9-be0622e8e8e3"
>   },
>   {
>     name: "My Clone Army",
>     appToken: "74ee0b5b-775e-4bee-974f-63e7f4d5bacb",
>     promoId: "fe693b26-b342-4159-8808-15e3ff7f8767"
>   },
>   {
>     name: "Train Miner",
>     appToken: "82647f43-3f87-402d-88dd-09a90025313f",
>     promoId: "c4480ac7-e178-4973-8061-9ed5b2e17954"
>   }
> ]

Yeah that will help me to update my key generate bot
Where did you find it ?
after I will update my bot I will send you keys
Send me your telegram

**Comment by daigia99xx** [comment]
How can I edit sir?
![Uploading Untitled.png…]()

**Comment by daigia99xx** [comment]
Can you update the code?
main.py file
I'm not familiar with code.
sorry to bother you

**Comment by miladesign** [comment]
> Yeah that will help me to update my key generate bot Where did you find it ? after I will update my bot I will send you keys Send me your telegram

thanks. i found it in one repo on github
i dont use this script. i made my own android app :)

**Comment by Microzibert** [comment]
![Screenshot_2024-08-06-18-31-56-076-edit_com kvassyu coding py](https://github.com/user-attachments/assets/36dd2208-372c-43c7-a941-2d88dacaec97)
 
I added appToken to the program, but it didn't give any results

**Comment by dima23113** [comment]
SupportedPromoGames = {
    "43e35910-c168-4634-ad4f-52fd764a843f": "Bike Ride 3D in Hamster FAM",
    "b4170868-cef0-424f-8eb9-be0622e8e8e3": "Chain Cube",
    "fe693b26-b342-4159-8808-15e3ff7f8767": "My Clone Army",
    "c4480ac7-e178-4973-8061-9ed5b2e17954": "Train Miner",
}



        for promo in response["promos"]:
            if promo[
                "promoId"
            ] in SupportedPromoGames and self.CheckPlayGroundGameState(promo, response):
                if promo["promoId"] == "43e35910-c168-4634-ad4f-52fd764a843f":
                    log.info(
                        f"[{self.account_name}] Starting Bike Ride 3D in Hamster FAM..."
                    )
                    time.sleep(2)
                    promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "d28721be-fd2d-4b45-869e-9f253b554e50")
                    if promoCode is not None:
                        log.info(
                            f"[{self.account_name}] Bike Ride 3D in Hamster FAM key: {promoCode}"
                        )
                        time.sleep(2)
                        log.info(
                            f"[{self.account_name}] Claiming Bike Ride 3D in Hamster FAM..."
                        )

                        self.ClaimPlayGroundGame(promoCode)
                        log.info(
                            f"[{self.account_name}] Playground game claimed successfully."
                        )
                if promo["promoId"] == "b4170868-cef0-424f-8eb9-be0622e8e8e3":
                    log.info(f"[]{self.account_name} Statring Chain Cube")
                    time.sleep(2)
                    promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "d1690a07-3780-4068-810f-9b5bbf2931b2")
                    log.info(
                        f"[{self.account_name}] Claiming Bike Chain Cube..."
                    )
                    self.ClaimPlayGroundGame(promoCode)
                    log.info(
                        f"[{self.account_name}] Playground game claimed successfully."
                    )
                if promo["promoId"] == "fe693b26-b342-4159-8808-15e3ff7f8767":
                    log.info(f"[]{self.account_name} Statring My Clone Army")
                    time.sleep(2)
                    promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "74ee0b5b-775e-4bee-974f-63e7f4d5bacb")
                    log.info(
                        f"[{self.account_name}] Claiming My Clone Army..."
                    )
                    self.ClaimPlayGroundGame(promoCode)
                    log.info(
                        f"[{self.account_name}] Playground game claimed successfully."
                    )
                if promo["promoId"] == "c4480ac7-e178-4973-8061-9ed5b2e17954":
                    log.info(f"[]{self.account_name} Statring Train Miner")
                    time.sleep(2)
                    promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "d28721be-fd2d-4b45-869e-9f253b554e50")
                    log.info(
                        f"[{self.account_name}] Claiming Train Miner..."
                    )
                    self.ClaimPlayGroundGame(promoCode)
                    log.info(
                        f"[{self.account_name}] Playground game claimed successfully."
                    )



 def GetPlayGroundBikeRideKey(self, promoID, appToken):
        clientId = f"{int(time.time() * 1000)}-{''.join(str(random.randint(0, 9)) for _ in range(19))}"

        log.info(f"[{self.account_name}] Getting Bike Ride 3D in Hamster FAM key...")

**Comment by Microzibert** [comment]
Thanks

**Comment by supmyhava** [comment]
> 74ee0b5b-775e-4bee-974f-63e7f4d5bacb

token and promoid for cube is good
but train and clone are not good
do you have the right ones ?

**Comment by dima23113** [comment]
> > 74ee0b5b-775e-4bee-974f-63e7f4d5bacb
> 
> token and promoid for cube is good but train and clone are not good do you have the right ones ?
It works for me. I think you need to add a pause between games because it works slower and slower with each game.

**Comment by ashwin8454** [comment]
> > games = [
> > {
> > name: "Riding Extreme 3D",
> > appToken: "d28721be-fd2d-4b45-869e-9f253b554e50",
> > promoId: "43e35910-c168-4634-ad4f-52fd764a843f"
> > },
> > {
> > name: "Chain Cube",
> > appToken: "d1690a07-3780-4068-810f-9b5bbf2931b2",
> > promoId: "b4170868-cef0-424f-8eb9-be0622e8e8e3"
> > },
> > {
> > name: "My Clone Army",
> > appToken: "74ee0b5b-775e-4bee-974f-63e7f4d5bacb",
> > promoId: "fe693b26-b342-4159-8808-15e3ff7f8767"
> > },
> > {
> > name: "Train Miner",
> > appToken: "82647f43-3f87-402d-88dd-09a90025313f",
> > promoId: "c4480ac7-e178-4973-8061-9ed5b2e17954"
> > }
> > ]
> 
> Yeah that will help me to update my key generate bot Where did you find it ? after I will update my bot I will send you keys Send me your telegram

Telegram: @kaztro_gaming

**Comment by Microzibert** [comment]
> > > 74ee0b5b-775e-4bee-974f-63e7f4d5bacb
> 
> token and promoid for cube is good but train and clone are not good do you have the right ones ?
> 
> It works for me. I think you need to add a pause between games because it works slower and slower with each game.

> SupportedPromoGames = { "43e35910-c168-4634-ad4f-52fd764a843f": "Bike Ride 3D in Hamster FAM", "b4170868-cef0-424f-8eb9-be0622e8e8e3": "Chain Cube", "fe693b26-b342-4159-8808-15e3ff7f8767": "My Clone Army", "c4480ac7-e178-4973-8061-9ed5b2e17954": "Train Miner", }
> 
> ```
>     for promo in response["promos"]:
>         if promo[
>             "promoId"
>         ] in SupportedPromoGames and self.CheckPlayGroundGameState(promo, response):
>             if promo["promoId"] == "43e35910-c168-4634-ad4f-52fd764a843f":
>                 log.info(
>                     f"[{self.account_name}] Starting Bike Ride 3D in Hamster FAM..."
>                 )
>                 time.sleep(2)
>                 promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "d28721be-fd2d-4b45-869e-9f253b554e50")
>                 if promoCode is not None:
>                     log.info(
>                         f"[{self.account_name}] Bike Ride 3D in Hamster FAM key: {promoCode}"
>                     )
>                     time.sleep(2)
>                     log.info(
>                         f"[{self.account_name}] Claiming Bike Ride 3D in Hamster FAM..."
>                     )
> 
>                     self.ClaimPlayGroundGame(promoCode)
>                     log.info(
>                         f"[{self.account_name}] Playground game claimed successfully."
>                     )
>             if promo["promoId"] == "b4170868-cef0-424f-8eb9-be0622e8e8e3":
>                 log.info(f"[]{self.account_name} Statring Chain Cube")
>                 time.sleep(2)
>                 promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "d1690a07-3780-4068-810f-9b5bbf2931b2")
>                 log.info(
>                     f"[{self.account_name}] Claiming Bike Chain Cube..."
>                 )
>                 self.ClaimPlayGroundGame(promoCode)
>                 log.info(
>                     f"[{self.account_name}] Playground game claimed successfully."
>                 )
>             if promo["promoId"] == "fe693b26-b342-4159-8808-15e3ff7f8767":
>                 log.info(f"[]{self.account_name} Statring My Clone Army")
>                 time.sleep(2)
>                 promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "74ee0b5b-775e-4bee-974f-63e7f4d5bacb")
>                 log.info(
>                     f"[{self.account_name}] Claiming My Clone Army..."
>                 )
>                 self.ClaimPlayGroundGame(promoCode)
>                 log.info(
>                     f"[{self.account_name}] Playground game claimed successfully."
>                 )
>             if promo["promoId"] == "c4480ac7-e178-4973-8061-9ed5b2e17954":
>                 log.info(f"[]{self.account_name} Statring Train Miner")
>                 time.sleep(2)
>                 promoCode = self.GetPlayGroundBikeRideKey(promo["promoId"], "d28721be-fd2d-4b45-869e-9f253b554e50")
>                 log.info(
>                     f"[{self.account_name}] Claiming Train Miner..."
>                 )
>                 self.ClaimPlayGroundGame(promoCode)
>                 log.info(
>                     f"[{self.account_name}] Playground game claimed successfully."
>                 )
> ```
> 
> def GetPlayGroundBikeRideKey(self, promoID, appToken): clientId = f"{int(time.time() * 1000)}-{''.join(str(random.randint(0, 9)) for _ in range(19))}"
> 
> ```
>     log.info(f"[{self.account_name}] Getting Bike Ride 3D in Hamster FAM key...")
> ```

I have a problem.the program just writes
 [Master HamsterKombat Bot][INFO] [A1] Getting Bike Ride 3D in Hamster FAM key...
and then freezes

**Comment by masterking32** [comment]
Added https://github.com/masterking32/MasterHamsterKombatBot/commit/256b7607743716383e0e54930f10e57c77e13e30
