### ISSUE TITLE
The spent amount result is not in total

### ISSUE THREAD

**Issue by ashwin8454** [masterking32/MasterHamsterKombatBot#110]
Upgraded 2 cards, but The spent result is not in total
![Screenshot 2024-08-07 153825](https://github.com/user-attachments/assets/78c4cad0-c4ec-4aa2-8946-bcd6734bdea1)

**Comment by bowler14** [comment]
there is no issue u didn't understand maybe see best card purchase completed that is last amount after that no card is purchased so final amount is same because nothing is changed I hope u understand
