### ISSUE TITLE
Unable to get account config data.

### ISSUE THREAD

**Issue by ashwin8454** [masterking32/MasterHamsterKombatBot#113]
![Screenshot 2024-08-07 211621](https://github.com/user-attachments/assets/7b7bd564-bb36-440e-ac7b-57b3ef71be8b)

**Comment by daigia99xx** [comment]
me too

**Comment by SilentWarrior1** [comment]
the same

**Comment by aman71711** [comment]
same for me any fix

**Comment by Pawansingh333** [comment]
yes same please fix [Master HamsterKombat Bot][INFO] [Account 1] Account ID: 795302543, Account detected as bot: False
[Master HamsterKombat Bot][INFO] [Account 1] Getting account config data...
[Master HamsterKombat Bot][ERROR] [Account 1] Unable to get account config data.

**Comment by sweetlilmre** [comment]
Just submitted a PR: https://github.com/masterking32/MasterHamsterKombatBot/pull/115
comment line 1068 in main.py with a # at the beginning of the line if you want to do this yourself:
`#            or "clickerConfig" not in AccountConfigData`

**Comment by Microzibert** [comment]
> Just submitted a PR: #115 comment line 1068 in main.py with a # at the beginning of the line if you want to do this yourself: `# or "clickerConfig" not in AccountConfigData`

Thanks

**Comment by tboy1337** [comment]
I have the same issue :/

**Comment by Pawansingh333** [comment]
> Just submitted a PR: #115 comment line 1068 in main.py with a # at the beginning of the line if you want to do this yourself: `# or "clickerConfig" not in AccountConfigData`

thanks working
