### ISSUE TITLE
auto_upgrade_min 

### ISSUE THREAD

**Issue by wwalah** [masterking32/MasterHamsterKombatBot#127]
The settings specify "auto_upgrade_min": 200_000_000 and "auto_upgrade_start": 200_000_000 
However a bot with a balance of 242M spent 142М, not 42+- as it should have, at the end a card was bought for 99M
![изображение](https://github.com/user-attachments/assets/1dc300f0-5f12-40d0-9bf2-8a0f151a2cc5)
![изображение](https://github.com/user-attachments/assets/45548e67-df14-4321-acc4-6ece0f35ca55)
![изображение](https://github.com/user-attachments/assets/d17839aa-e242-44d8-a50c-7fee92fea59c)

**Comment by sweetlilmre** [comment]
Your final balance was 102.5m, the card purchased was 99.69m, so the total before purchase was 202.19m, which is above the threshold and technically correct. For the behaviour you want, the code would have to make a 2nd check prior to the card purchase. The author will have to decide if this is intended behaviour or a bug.

**Comment by epis78** [comment]
esp. purchase of high level cards which are usually expensive, causes the balance to drop below the set threshold. a further check seems necessary to prevent this or an option to control the behavior.
