### ISSUE TITLE
Unable to get account config data.

### ISSUE THREAD

**Issue by camillo1990** [masterking32/MasterHamsterKombatBot#129]
Hi! I've got a bug: Unable to get account config dat
I didn't change the config, everything worked fine before. 

Log:
[Master HamsterKombat Bot][ERROR] [Account 1] Unable to get account config data.

**Comment by camelot-rus** [comment]
comment line 1068 in main.py with a # at the beginning of the line if you want to do this yourself:
#            or "clickerConfig" not in AccountConfigData

**Comment by camelot-rus** [comment]
#    or "clickerConfig" not in AccountConfigData

**Comment by camelot-rus** [comment]
comment line 1068 in main.py with a # at the beginning of the line if you want to do this yourself:
`#    or "clickerConfig" not in AccountConfigData`

**Comment by camillo1990** [comment]
It's working! Thank you so much!

> comment line 1068 in main.py with a # at the beginning of the line if you want to do this yourself: `# or "clickerConfig" not in AccountConfigData`

It's working! Thank you so much! ❤️
