### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by ItsAmirAT** [masterking32/MasterHamsterKombatBot#132]
i am using proxy for my accounts, and in terminal it shows the real ip, is it a problem ?

_[Master HamsterKombat Bot][INFO] 2024-08-09 16:41:27 [Name] IP: my.ip.here Company: Company Name Here Country: DE_
i changed ip and company name for this example

**Comment by Microzibert** [comment]
Yes, I have the same problem. The old code didn't have this problem

**Comment by AmirhN1382** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/128#issuecomment-2278569291

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/133?converting=1#discussioncomment-10290865
