### ISSUE TITLE
Stop on getting account data 

### ISSUE THREAD

**Issue by wh1ter0z** [masterking32/MasterHamsterKombatBot#134]
![Screenshot_20240810_093115_Termius](https://github.com/user-attachments/assets/115a1c3c-d9ea-4448-ac71-99869a64f3ea)

I use 3 account 
Server location : iran 
I run without proxy 
Last update of your bot 
 Its about 1 day no work and stops on getting accoumt data 
Also i have to add this : Account not detected as bot

**Comment by masterking32** [comment]
Try using a different location instead of Iran.
