### ISSUE TITLE
Minigame issue

### ISSUE THREAD

**Issue by SilentWarrior1** [masterking32/MasterHamsterKombatBot#137]
Greetings, i've got an error in minigame:
[Master HamsterKombat Bot][ERROR] 2024-08-11 08:11:21 [Lucinda] Status code is not 200
[Master HamsterKombat Bot][ERROR] 2024-08-11 08:11:21 [Lucinda] Response: {"error_code":"DAILY_KEYS_MINI_GAME_TIME_IS_OVER","error_message":"DailyKeysMiniGame remain -14.171999999999997 seconds"}
[Master HamsterKombat Bot][ERROR] 2024-08-11 08:11:21 [Lucinda] Unable to claim mini game.

**Comment by masterking32** [comment]
The app will take it on the next run don't worry.

**Comment by SilentWarrior1** [comment]
> The app will take it on the next run don't worry.

no, it doesn't  play minigames anymore :(
