### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Pawansingh333** [masterking32/MasterHamsterKombatBot#141]
Master HamsterKombat Bot][INFO] 2024-08-11 11:03:46 Starting all accounts...
[Master HamsterKombat Bot][INFO] 2024-08-11 11:03:46 [Account 1] Starting account...
[Master HamsterKombat Bot][INFO] 2024-08-11 11:03:46 [Account 1] Getting basic account data...
[Master HamsterKombat Bot][ERROR] 2024-08-11 11:03:49 [Account 1] Status code is not 200
[Master HamsterKombat Bot][ERROR] 2024-08-11 11:03:49 [Account 1] Response: Internal server error
[Master HamsterKombat Bot][ERROR] 2024-08-11 11:03:49 [Account 1] Unable to get account basic data. 

Please Fix This

**Comment by masterking32** [comment]
Internal server error
