### ISSUE TITLE
error

### ISSUE THREAD

**Issue by supmyhava** [masterking32/MasterHamsterKombatBot#143]
[Master HamsterKombat Bot][INFO] 2024-08-11 21:39:24 [Moshe 1] Account ID: 1354016074, Account
detected as bot: False 
[Master HamsterKombat Bot][INFO] 2024-08-11 21:39:24 [Moshe 1] Getting account config data... 
[Master HamsterKombat Bot][ERROR] 2024-08-11 21:39:25 [Moshe 1] Status code is not 200 
[Master HamsterKombat Bot][ERROR] 2024-08-11 21:39:25 [Moshe 1] Response: NOT_FOUND
[Master HamsterKombat Bot][INFO] 2024-08-11 21:39:25 [Moshe 1] Account config version: ae1ZEH61yb8xYU4OOigHqqvH1eta8xx2b3lY75wWppk
[Master HamsterKombat Bot][INFO] 2024-08-11 21:39:25 [Moshe 1] Decoding daily cipher...  
[Master HamsterKombat Bot][INFO] 2024-08-11 21:39:25 [Moshe 1] Getting account data...
[Master HamsterKombat Bot][INFO] 2024-08-11 21:39:25 [Moshe 1] Account Balance Coins: 19.78m, Available Taps: 9000, Max Taps: 9000, Total Keys: 135, Balance Keys: 135

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/commit/1d811126e3004d094e0c1c31a6cc4d57c5ce7be2
