### ISSUE TITLE
telegram logs stopped working

### ISSUE THREAD

**Issue by bangtony2** [masterking32/MasterHamsterKombatBot#144]
**telegram logs stopped working**

**Comment by masterking32** [comment]
Use the new version of the config file.
https://github.com/masterking32/MasterHamsterKombatBot/blob/d0d379989a56f9df9338a98ae1758af01a9b850b/config.py.example#L102

**Comment by bangtony2** [comment]
still doesn't work.

**Comment by bangtony2** [comment]
> Use the new version of the config file.
> 
> https://github.com/masterking32/MasterHamsterKombatBot/blob/d0d379989a56f9df9338a98ae1758af01a9b850b/config.py.example#L102

still doesn't work.

**Comment by AlexArGC** [comment]
> > Use the new version of the config file.
> > https://github.com/masterking32/MasterHamsterKombatBot/blob/d0d379989a56f9df9338a98ae1758af01a9b850b/config.py.example#L102
> 
> still doesn't work.

Pay attention to what works for other people. Look for errors.

**Comment by bangtony2** [comment]
> > > Use the new version of the config file.
> > > https://github.com/masterking32/MasterHamsterKombatBot/blob/d0d379989a56f9df9338a98ae1758af01a9b850b/config.py.example#L102
> > 
> > 
> > still doesn't work.
> 
> Pay attention to what works for other people. Look for errors.

you're a genius, open your eyes and look at the last commit.
