### ISSUE TITLE
Error getting IP

### ISSUE THREAD

**Issue by joshuazzz1** [masterking32/MasterHamsterKombatBot#160]
[Account 1] Error: Invalid \escape: line 1 column 154 (char 153)
[Account 1] Failed to get IP.

I keep getting this error, but when I try to use any random VPN, it magically disappears. Using latest version

**Comment by masterking32** [comment]
There is nothing we can do about that, The Hamster server returns an invalid JSON, comment  these lines:
https://github.com/masterking32/MasterHamsterKombatBot/blob/2c42aada07c5b7f7116746443fc0dd764a4fc9b8/main.py#L1226
```
        if ipResponse is None:
            log.error(f"[{self.account_name}] Failed to get IP.")
            self.SendTelegramLog(
                f"[{self.account_name}] Failed to get IP.", "other_errors"
            )
            return
```
or try with a different ISP or IP.

**Comment by joshuazzz1** [comment]
> There is nothing we can do about that, The Hamster server returns an invalid JSON, comment these lines:
> 
> https://github.com/masterking32/MasterHamsterKombatBot/blob/2c42aada07c5b7f7116746443fc0dd764a4fc9b8/main.py#L1226
> 
> ```
>         if ipResponse is None:
>             log.error(f"[{self.account_name}] Failed to get IP.")
>             self.SendTelegramLog(
>                 f"[{self.account_name}] Failed to get IP.", "other_errors"
>             )
>             return
> ```

Okay I will do that but first I just want to be sure, Is it a safe thing to do? or there will be higher chances of Hamster suspecting my account? Please reply so I know if it better to remove this code or just use a VPN while running your script.

**Comment by masterking32** [comment]
> > There is nothing we can do about that, The Hamster server returns an invalid JSON, comment these lines:
> > https://github.com/masterking32/MasterHamsterKombatBot/blob/2c42aada07c5b7f7116746443fc0dd764a4fc9b8/main.py#L1226
> > 
> > ```
> >         if ipResponse is None:
> >             log.error(f"[{self.account_name}] Failed to get IP.")
> >             self.SendTelegramLog(
> >                 f"[{self.account_name}] Failed to get IP.", "other_errors"
> >             )
> >             return
> > ```
> 
> Okay I will do that but first I just want to be sure, Is it a safe thing to do? or there will be higher chances of Hamster suspecting my account? Please reply so I know if it better to remove this code or just use a VPN while running your script.

If you comment on these lines of code, a request will be sent; you will only disable the display of errors.
