### ISSUE TITLE
forgotten comma

### ISSUE THREAD

**Issue by fdrov** [masterking32/MasterHamsterKombatBot#164]
Hello! Could you please fix a small issue. Just add a comma at the end of line 1102. Thank you!
https://github.com/masterking32/MasterHamsterKombatBot/blob/2c42aada07c5b7f7116746443fc0dd764a4fc9b8/main.py#L1102C70-L1102C80

**Comment by 4E614EBread** [comment]
That's why he added the default (level) = "other_errors" to the sendtelegram function :P
