### ISSUE TITLE
Stuck on game keys

### ISSUE THREAD

**Issue by Metercedes** [masterking32/MasterHamsterKombatBot#173]
For unknown reasons, it hangs and does not continue when processing event keys into the account. Sometimes it continues but most of the time it freezes. I can't figure out why, but that's the situation.

VPN is enabled and running at a good speed (ProtonVPN)
From a random site I found, I added a proxy to the code and it works.

![image](https://github.com/user-attachments/assets/1adc4287-e181-41cf-8ff7-8c2e5a6b18e1)

**Comment by ashwin8454** [comment]
after that getting error
![Screenshot 2024-08-15 191038](https://github.com/user-attachments/assets/8c63411a-3f9b-4c89-b194-8ab110555487)

**Comment by Metercedes** [comment]
> after that getting error ![Screenshot 2024-08-15 191038](https://private-user-images.githubusercontent.com/177106339/358236485-8c63411a-3f9b-4c89-b194-8ab110555487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzE1MzcsIm5iZiI6MTcyMzczMTIzNywicGF0aCI6Ii8xNzcxMDYzMzkvMzU4MjM2NDg1LThjNjM0MTFhLTNmOWItNGM4OS1iMTk0LThhYjExMDU1NTQ4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNDEzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzBmMzYxNmNhNjNjOGY1NzZlZmY3MDUxYjgyNDQ2YjZjNTExOGY5Y2EyNzliNjdjYjY2NzA5YWM2MTdkMjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3_LlrBGWSls3ElMaYYMGHnogLPG2qM8zpP_ZIAHRtDk)

This is due network. The problem which I encounter is different. It's not about the network, just the code is failing to redeem the key. Actually, in such cases, it would be good to do that manually if they'd expose the code to logs.

**Comment by ashwin8454** [comment]
yeah. but the key gen is too low. cant be increase the speed?

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/commit/7e71df4b3b9a06e1edddd594fac1b686e3a9692b
https://github.com/masterking32/MasterHamsterKombatBot/commit/dc851ef99c1d5b0ca3628a3357f04e42f6c9d23c

**Comment by Metercedes** [comment]
> https://github.com/masterking32/MasterHamsterKombatBot/commit/7e71df4b3b9a06e1edddd594fac1b686e3a9692b
> 
> https://github.com/masterking32/MasterHamsterKombatBot/commit/dc851ef99c1d5b0ca3628a3357f04e42f6c9d23c

Due to lack of my knowledge, I must ask you what shall we do with these codes? Could you please explain it?

**Comment by masterking32** [comment]
> > [7e71df4](https://github.com/masterking32/MasterHamsterKombatBot/commit/7e71df4b3b9a06e1edddd594fac1b686e3a9692b)
> > [dc851ef](https://github.com/masterking32/MasterHamsterKombatBot/commit/dc851ef99c1d5b0ca3628a3357f04e42f6c9d23c)
> 
> Due to lack of my knowledge, I must ask you what shall we do with these codes? Could you please explain it?

If you are not a programmer, you don't need to understand the code. Just update/download the project and use the latest version.
