### ISSUE TITLE
Bot Detection Message Not Available

### ISSUE THREAD

**Issue by Metercedes** [masterking32/MasterHamsterKombatBot#180]
In the section that shows whether our account was previously flagged as ‘Bot’ by the server, it says `[Master HamsterKombat Bot][INFO] 2024-08-15 22:18:27 [Account 1] Account ID: <they wrote my ID here>, Account Name:`. do you think I am in danger? Because it used to say ‘No’ directly that my account was not a bot, but now it says this. Is that normal?

![image](https://github.com/user-attachments/assets/e94f27d4-4a6c-477a-8192-13e6a3954324)

**Comment by joshuazzz1** [comment]
No, You're not in danger. It's because of a new API change and I guess you can't check anymore if your account is flagged as a Bot after these new changes.

**Comment by Metercedes** [comment]
> No, You're not in danger. It's because of a new API change and I guess you can't check anymore if your account is flagged as a Bot after these new changes.

I get it, I wonder if @masterking32 can fix and also add avoid flag detection?

**Comment by joshuazzz1** [comment]
> > No, You're not in danger. It's because of a new API change and I guess you can't check anymore if your account is flagged as a Bot after these new changes.
> 
> I get it, I wonder if @masterking32 can fix and also add avoid flag detection?

Nothing really changes for the Bot after this API change, only the fact that you can't check if your account is flagged. I don't think the developer can do anything about that like adding it the checks back, but let's see.
