### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by camelot-rus** [masterking32/MasterHamsterKombatBot#182]
`[Master HamsterKombat Bot][ERROR] 2024-08-16 18:18:00 [Account 1 the_pessage] Error: HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/login-client (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))
[Master HamsterKombat Bot][ERROR] 2024-08-16 18:18:00 [Account 1 the_pessage] Error: HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/login-client (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))
[Master HamsterKombat Bot][ERROR] 2024-08-16 18:18:00 [Account 1 the_pessage] Unable to get Merge Away key.`

**Comment by camelot-rus** [comment]
![Uploading Снимок экрана 2024-08-16 181944.png…]()

**Comment by camelot-rus** [comment]
![Uploading Снимок экрана 2024-08-16 181944.png…]()

**Comment by camelot-rus** [comment]
![Uploading photo_2024-08-16_18-41-00.jpg…]()

**Comment by camelot-rus** [comment]
![photo_2024-08-16_18-41-00](https://github.com/user-attachments/assets/546e07c0-72d0-4e50-9920-423b68b8ace6)

**Comment by Fy0urM** [comment]
It's not a bot problem, it's a connection problem, possibly a proxy problem
