### ISSUE TITLE
Show best cards without buying them

### ISSUE THREAD

**Issue by Unclezz** [masterking32/MasterHamsterKombatBot#183]
Hello, is there any way we can get the bot working only to show what are the current best cards available to buy but without actually buying them?

**Comment by sweetlilmre** [comment]
I think you can, this is technically a 'bug' or at least interesting behaviour:
Set `parallel_upgrades_max_price_per_hour` to 0 and `show_num_buy_options` to the number of ranked options you'd like to see. Make sure that `wait_for_best_card` is True.
Report your findings :)
