### ISSUE TITLE
New Game: Twerk Race 3D

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#185]
"name": "Twerk Race 3D",
        "appToken": "61308365-9d16-4040-8bb0-2f4a4c69074c",
        "promoId": "61308365-9d16-4040-8bb0-2f4a4c69074c",

**Comment by nevs83** [comment]
[https://github.com/masterking32/MasterHamsterKombatBot/issues/181](url)

**Comment by mtrisme** [comment]
not working for me 
shows this
![image](https://github.com/user-attachments/assets/076def5c-0078-46c5-b945-cdc5769da4f7)
