### ISSUE TITLE
Global key generation problem (maybe)

### ISSUE THREAD

**Issue by Vladik01-11** [masterking32/MasterHamsterKombatBot#188]
I suggest you familiarize yourself with the mini-game execution system, namely its requests for event registration:

* Reading Extreme 3D: the generation corresponds to the original.

* Chain Cube: alas, I do not know here, this game refused to run on my device

* My clone army: generation does NOT match the original:
* * When generation is underway, another "eventType" is sent: "MiniQuest"

* Train Miner: the generation does NOT match the original:
* * When the generation is underway, another "eventType" is sent: "hitStatue" p.s. can there be other types?

* Merge Away!: the generation does NOT match the original:
* * When generation is in progress, an OPTIONS request is always sent before the POST request, the POST itself is sent with "eventType": "spend-energy" p.s. can there be other types?

* Twerk: the generation does NOT match the original:
* * When the generation is underway, another "eventId": "StartLevel" is sent, and "eventOrigin": "undefined" + as @nevs83 noted, it is in this game that the key is issued for the 11th request

As I believe, because of all this discrepancy, accounts may be demolished in the future for bot farming, which is why I would strongly recommend that those who really use these bots or key generators do not use them.
_yes, the statement is strong_

All the research was done on the latest versions of the games. If I was wrong somewhere, correct me.

**Comment by 8wx** [comment]
@Vladik01-11 Do you have a working generator that has all those issues worked out?

**Comment by 8wx** [comment]
> > @Vladik01-11 Do you have a working generator that has all those issues worked out?
> 
> no, I just analyzed all the games and published them here so that knowledgeable people could draw their conclusions and make changes to the code :3

What's the eventType in the Riding Bike game? "undefined"?

I see the eventOrigin is set to undefined for all games.

**Comment by nevs83** [comment]
In previous games there was random UUID as eventId. But here i see static string "StartLevel"

**Comment by masterking32** [comment]
Thanks for the report. Could you please review all the game requests and share your findings here?

**Comment by masterking32** [comment]
> > Could you please review all the game requests and share your findings here?
> 
> English is not my native language, so will you excuse me so that I check all the requests from the games or look at your commit? commit looks similar to what I was talking about, but it misses the OPTIONS request for the Merge Away game and the ambiguity of the last added game

If you can, please send me the log of all the game's HTTP requests. Also, the option request already exists:
https://github.com/masterking32/MasterHamsterKombatBot/blob/25a43909efec0decc76cac121585f22adca1d3ca/main.py#L1024

**Comment by joshuazzz1** [comment]
Based on another repo on github twerk has `eventType` as `StartLevel` and cube has it as `cube_sent`.

**Comment by tboy1337** [comment]
check https://github.com/masterking32/MasterHamsterKombatBot/discussions/193 this seems to be a better solution.

**Comment by masterking32** [comment]
> > If you can, please send me the log of all the game's HTTP requests
> 
> Check Mail, **Don't make it public** ![explorer_khuqoZPZLl](https://private-user-images.githubusercontent.com/70571714/358838043-d5c12aad-9dbc-4403-b8b8-65099ca13e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTU1NTMsIm5iZiI6MTcyMzkxNTI1MywicGF0aCI6Ii83MDU3MTcxNC8zNTg4MzgwNDMtZDVjMTJhYWQtOWRiYy00NDAzLWI4YjgtNjUwOTljYTEzZTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE3MjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MzNlYmExNDI0N2I3OGYwZGFlOGIxYmZjZGIwNDg0YTNlOGZlOTBjNDZkYzEwN2JkNWFkODI1NTVjYzIyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9hMqt7Jj2iRiT_aUfL1i8W9c84T_rZXOCoZ-2DyxEk)

The password is wrong!

**Comment by tboy1337** [comment]
Why reinvent the wheel, just use delasy's key generator which he updates every day https://github.com/masterking32/MasterHamsterKombatBot/discussions/193

**Comment by masterking32** [comment]
The project has been updated, I'm going to close this.
Thanks for your report.
