### ISSUE TITLE
HamsterKombat

### ISSUE THREAD

**Issue by litvin1973** [masterking32/MasterHamsterKombatBot#194]
Здравствуйте! Ваши код самый лучший из всех, которые я перебрал. Искал долго, перепробовал многие. Ваш ЛУЧШИЙ! В чатах с 
 другими ботами целыми днями что то фиксят, постоянные сбои, а Ваш HamsterKombat работает как швейцарские часы! Я к чему все это пишу? Почему Вы не делаете ботов к другим проектам? Например: PocketFi, OKXracer и подобные? ООчень буду ждать новых ботов. Всех Вам благ!

**Comment by AmirhN1382** [comment]
Hey! Check out the project's ReadMe now. [MasterCryptoFarmBot](https://github.com/masterking32/mastercryptofarmbot) will be doing what you asked :P
