### ISSUE TITLE
bug playground

### ISSUE THREAD

**Issue by parafius** [masterking32/MasterHamsterKombatBot#199]
![image](https://github.com/user-attachments/assets/d789e0fd-33df-4d7c-9495-3be0d231d433)
update doesnt help

**Comment by nevs83** [comment]
![image](https://github.com/user-attachments/assets/c99773d4-bf95-4ca8-982d-3a2349020bd4)
you probably don't have the latest version.

**Comment by nevs83** [comment]
> ![image](https://private-user-images.githubusercontent.com/178029177/358931013-d789e0fd-33df-4d7c-9495-3be0d231d433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMTEwMDQsIm5iZiI6MTcyNDAxMDcwNCwicGF0aCI6Ii8xNzgwMjkxNzcvMzU4OTMxMDEzLWQ3ODllMGZkLTMzZGYtNGQ3Yy05NDk1LTNiZTBkMjMxZDQzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxOTUxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTgxMDBhMDk4NDMzNzA3OGQyZTA1ZDQ0ODc4M2E0MTJlOWMyZGQzNjQ1ZjViODk0OGNmYzY3YTczMDkzZWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3iBgeC80FNAEuziz7c7JC9T7e-yXBf3Qm6rudycacgw) update doesnt help

![image](https://github.com/user-attachments/assets/a27b3190-c2aa-49ef-b30b-48bf2a704e4c)
I just checked it out. Everything works
