### ISSUE TITLE
Unable to get Polysphere Key

### ISSUE THREAD

**Issue by bowler14** [masterking32/MasterHamsterKombatBot#215]
Unable to get Polysphere Key : Art Puzzle Game 
it almost 12+ hours still can't collect key for this game

**Comment by Fy0urM** [comment]
> Unable to get Polysphere Key : Art Puzzle Game it almost 12+ hours still can't collect key for this game

u update bot to latest version? or edit script by youself? which value on https://github.com/masterking32/MasterHamsterKombatBot/blob/f4126833162817faff268b7f51ac1529aa7a2b8a/main.py#L1031
