### ISSUE TITLE
New Ideas...

### ISSUE THREAD

**Issue by Metercedes** [masterking32/MasterHamsterKombatBot#216]
I'm going to ask for a few new ideas. I personally think they could be useful.

1) Get the Daily Combo data from this website https://hamsterkombo.com/ and implement it.

2) Make it Achievement-orientated, for example, there is a ‘Rescue Team’ achievement, but I couldn't do it because that card in Specials expired, so I will probably never be able to unlock it again.

**Comment by masterking32** [comment]
Duplicate:
https://github.com/masterking32/MasterHamsterKombatBot/issues/69
