### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#219]
سلام رفیق
دو بازی جدید اضافه شده که وقتی خواستید آن را اضافه کنید این باگ هم درست کنید ، من اسکریپت رو داخل سرور دائمی روشن گذاشتم و فقط سه تا بازی poly - merge - twerk را کلید هاشون میزنه و بقیه هنوز کاری نکرده 
و اینکه هر سه ساعت پروفیت هم بگیره

**Comment by Fy0urM** [comment]
> سلام رفیق دو بازی جدید اضافه شده که وقتی خواستید آن را اضافه کنید این باگ هم درست کنید ، من اسکریپت رو داخل سرور دائمی روشن گذاشتم و فقط سه تا بازی poly - merge - twerk را کلید هاشون میزنه و بقیه هنوز کاری نکرده و اینکه هر سه ساعت پروفیت هم بگیره

سلام دوست عزیز، ببخشید اگر اشتباهی هست، من از مترجم گوگل استفاده می کنم. اگر از ربات به شکل اصلی خود استفاده می کنید، به طور پیش فرض در هر 1 چرخه 3 بازی انجام می شود، پارامتر max_promo_games_per_round مسئول تعداد بازی ها در هر چرخه است و به طور پیش فرض 3 است.

**Comment by ParsapythonLv** [comment]
thanks 🔥
