### ISSUE TITLE
new game issue

### ISSUE THREAD

**Issue by bowler14** [masterking32/MasterHamsterKombatBot#226]
playground game Mow and Trim already claimed.
[Master HamsterKombat Bot][INFO] [bot- 2] Playground game Mud Racing already claimed.

it shows message that key is collected but in game its not collected it still show (0/4)
i did all new changes in script but dont know whats wrong

**Comment by afdah** [comment]
Working on my end.

**Comment by ashwin8454** [comment]
> playground game Mow and Trim already claimed. [Master HamsterKombat Bot][INFO] [bot- 2] Playground game Mud Racing already claimed.
> 
> it shows message that key is collected but in game its not collected it still show (0/4) i did all new changes in script but dont know whats wrong

(The mini games are designed to randomly shuffle their order to avoid detection as a bot, making it appear more like human behavior)

**Comment by ashwin8454** [comment]
> playground game Mow and Trim already claimed. [Master HamsterKombat Bot][INFO] [bot- 2] Playground game Mud Racing already claimed.
> 
> it shows message that key is collected but in game its not collected it still show (0/4) i did all new changes in script but dont know whats wrong

The mini games are designed to randomly shuffle their order to avoid detection as a bot, making it appear more like human behavior.

**Comment by ashwin8454** [comment]
> playground game Mow and Trim already claimed. [Master HamsterKombat Bot][INFO] [bot- 2] Playground game Mud Racing already claimed.
> 
> it shows message that key is collected but in game its not collected it still show (0/4) i did all new changes in script but dont know whats wrong

Because of The mini games are designed to randomly shuffle their order to avoid detection as a bot, making it appear more like human behavior

**Comment by Fy0urM** [comment]
> Because of The mini games are designed to randomly shuffle their order to avoid detection as a bot, making it appear more like human behavior

Shuffling has no effect on the message being displayed, the bot first receives a list of games from the server, shuffles them, and only then checks the possibility of a key, if the daily number of keys for the game is not entered, it tries to get a key.


> it shows message that key is collected but in game its not collected it still show (0/4)
> i did all new changes in script but dont know whats wrong

You may have made some changes to the script, make sure you have the latest version of the bot from the repository, don't make any changes to it except config.py and check it out

**Comment by tboy1337** [comment]
working fine for me.

**Comment by Fy0urM** [comment]
I think maybe issue starter just opened the games page before getting the keys by bot and then after getting the keys by bot just did not refresh the games page

**Comment by Fy0urM** [comment]
> [bot- 2]

or given that he has it in his log, he has multiple accounts and he's just looking at the wrong account.

**Comment by Fy0urM** [comment]
> [Master HamsterKombat Bot][INFO] [bot- 2] Playground game Mud Racing already claimed.

Also, given that he has no timestamp in his log, he probably has either an old version of the bot or a modified one, although he says he has the latest and no modifications.
my current bot output as example
![image](https://github.com/user-attachments/assets/6ec63ff7-c0ef-4ed9-a5d0-d9a2a8d0e50d)

**Comment by bowler14** [comment]
> > [bot- 2]
> 
> or given that he has it in his log, he has multiple accounts and he's just looking at the wrong account.

Its Working Fine now i don't know what's wrong yesterday , yes i have multiple account and i double checked it That i was checking right account  but anyways all working now Thanks for Response

**Comment by bowler14** [comment]
it's working Now Thanks for Your help
