### ISSUE TITLE
Unable to get daily keys mini game.

### ISSUE THREAD

**Issue by supmyhava** [masterking32/MasterHamsterKombatBot#245]
[Master HamsterKombat Bot][ERROR] 2024-08-28 00:18:46 [11] Unable to get daily keys mini game.
probably because the new mini game that just added
there is a way to make it work ?

**Comment by Pawansingh333** [comment]
yes please update your bot

**Comment by ZProtons** [comment]
he released the new mini game update? I can't see it in the readme.

**Comment by Pawansingh333** [comment]
new mini game not added in bot

**Comment by tboy1337** [comment]
Duplicate of https://github.com/masterking32/MasterHamsterKombatBot/issues/236
