### ISSUE TITLE
New Playground Game Cafe Dash

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#249]
'name': 'Cafe Dash',
        'appToken': 'bc0971b8-04df-4e72-8a3e-ec4dc663cd11',
        'promoId': 'bc0971b8-04df-4e72-8a3e-ec4dc663cd11',

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/commit/a0e9e1b672d1b92a89b1ff97715f0ea98bb7429b
