### ISSUE TITLE
Please fix : Unable to get daily keys mini game.

### ISSUE THREAD

**Issue by MeninSun** [masterking32/MasterHamsterKombatBot#258]
Please fix for the puzzle game, thank you.

![image](https://github.com/user-attachments/assets/c96b6c9f-fb1c-4335-9bcd-0091ad62e254)

**Comment by masterking32** [comment]
Duplicate: https://github.com/masterking32/MasterHamsterKombatBot/issues/236

**Comment by MeninSun** [comment]
> Duplicate: #236

Thank you
