### ISSUE TITLE
Whatever I Do I Can't Mark Minigames as Completed

### ISSUE THREAD

**Issue by Metercedes** [masterking32/MasterHamsterKombatBot#265]
Weird thing is when I enter the Minigames, the key thing is showing up as completed but Hex game can't be completed I didn't get it. We need a bot which plays Hex game as well.

![image](https://github.com/user-attachments/assets/8d89184a-2589-40bf-b0c1-eee9519f851d)

![image](https://github.com/user-attachments/assets/fb35531c-1ed7-46e0-b85d-aaa7a97e5b55)

**Comment by limbonux** [comment]
It appeared complete to me after several rounds of play.
The reward started at 100 million, then decreased until it reached 100,000, and then it appeared as complete for me. 
![IMG_20240829_180540](https://github.com/user-attachments/assets/4ffc8850-1138-483e-b696-edc7954cb0e9)

**Comment by nevs83** [comment]
are you using the latest version of the bot?

**Comment by Metercedes** [comment]
Does the bot autoplays this till it completes?

kt, 29.08.2024 18:08 Suleiman Alhagami ***@***.***> rašė:

**Comment by nevs83** [comment]
"auto_finish_mini_game": True,  # Enable auto finish mini game by setting it to True, or set it to False to disable.   TRUE?

**Comment by Metercedes** [comment]
Its enabled (True)

kt, 29.08.2024 18:17 nevs83 ***@***.***> rašė:

**Comment by nevs83** [comment]
I have a mini game completed on all my accounts
![image](https://github.com/user-attachments/assets/77be2e0e-877e-4896-a016-964b5e8b892a)
you have downloaded the latest version from the main branches?

**Comment by Metercedes** [comment]
> I have a mini game completed on all my accounts
> 
> ![image](https://github.com/user-attachments/assets/77be2e0e-877e-4896-a016-964b5e8b892a)
> 
> you have downloaded the latest version from the main branches?

Yep I did

**Comment by nevs83** [comment]
Do you have multiple accounts?

**Comment by Metercedes** [comment]
> Do you have multiple accounts?

No just 1

**Comment by nevs83** [comment]
it is best to remove the bot and download and configure it again. 
this is if you do not delve into the reason for skipping the mini-game

**Comment by Metercedes** [comment]
> it is best to remove the bot and download and configure it again. 
> 
> this is if you do not delve into the reason for skipping the mini-game

Well in fact, I always delete files if an update comes and configure it from zero

**Comment by nevs83** [comment]
can you throw off the version that you are using? just delete the Authorization Bearer ******

**Comment by Metercedes** [comment]
> can you throw off the version that you are using? just delete the Authorization Bearer ******

Here is the config.py file which I dowloaded almost 6hrs ago:
[](https://drive.google.com/file/d/1jUndPx2ks00RVmw_DfecFbxqUDW6FiHf/view?usp=sharing)

**Comment by Metercedes** [comment]
> ![image](https://github.com/user-attachments/assets/9d708f32-4fb4-4b82-af96-14ecec999bff)
> 
> you downloaded the bot completely, didn't you? or just a file config.py

Yes I also have this in my logs however the minigame doesnt seem to be completed

**Comment by Metercedes** [comment]
> ![image](https://private-user-images.githubusercontent.com/6564258/362788303-9d708f32-4fb4-4b82-af96-14ecec999bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDg3MjQsIm5iZiI6MTcyNDk0ODQyNCwicGF0aCI6Ii82NTY0MjU4LzM2Mjc4ODMwMy05ZDcwOGYzMi00ZmI0LTRiODItYWY5Ni0xNGVjZWM5OTliZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTYyMDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWFkNDViNzA5YWM0MGU3YmNiNjY3NDc5MTU4YjkxYjUxMjJiNTQwMjJkOWQ0NjVkYjc0ZjNiYzRkNWU1NDM4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7za4O-PnvUzR-aepvvc3iCkZquMJqqmEsUKj3Apxk9s) you downloaded the bot completely, didn't you? or just a file config.py

Check my logs:

![image](https://github.com/user-attachments/assets/95ffb318-f361-468e-8c66-8b4ab3929839)

**Comment by nevs83** [comment]
it was necessary to start with this))) there is a limit on getting coins. now it is equal to your hourly yield * 28.8. a random part of the coins is mined at 1 time. he will do this 10-20 times and only after that the mini-game will be completed

**Comment by nevs83** [comment]
this is the normal operation of the bot. leave it for a couple of hours and you'll see for yourself

**Comment by Metercedes** [comment]
> this is the normal operation of the bot. leave it for a couple of hours and you'll see for yourself

So bot need to restart itself every time to play that game.

**Comment by nevs83** [comment]
Yes, every time the bot restarts, it will play the game. it will not exhaust its limit yet. the limit is calculated according to the formula. earn on hour * 28.8

**Comment by nevs83** [comment]
to check, I turned off all other modes and left only the mini-game mode. and after 1-2 hours, he completed the task

**Comment by Metercedes** [comment]
> to check, I turned off all other modes and left only the mini-game mode. and after 1-2 hours, he completed the task

I get it now thank you very much!
