### ISSUE TITLE
new setting in config

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#269]
I don't quite understand how the new setting in the config works
```
"mg_max_tiles_points_percent": 20, # Maximum value for using points in percentages for the mini game Tiles
``` 
Сan someone explain how the setting works and how to calculate it correctly.
Thanks

**Comment by MeninSun** [comment]
> I don't quite understand how the new setting in the config works
> 
> ```
> "mg_max_tiles_points_percent": 20, # Maximum value for using points in percentages for the mini game Tiles
> ```
> 
> Сan someone explain how the setting works and how to calculate it correctly. Thanks

I guess, maybe 20% reward from total reward/day, for example : if total reward/day is 100M, you will get 20M/cycle.
