### ISSUE TITLE
mini-game bug

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#273]
![Screenshot_2024-08-30-08-21-10-163_ir ilmili telegraph](https://github.com/user-attachments/assets/ae5a777b-837d-49bf-bf81-eb018410d27d)
The bot is trying to solve the minigame, but it can't

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/268
