### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by ali-ghanati** [masterking32/MasterHamsterKombatBot#279]
for 2 days i keep getting connection errors and tried every vpn possible
`[Master HamsterKombat Bot][INFO] 2024-08-30 12:35:12 [Account 1] Getting account upgrades...
[Master HamsterKombat Bot][ERROR] 2024-08-30 12:35:32 [Account 1] Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
`

even updating didn't help me

**Comment by ali-ghanati** [comment]
`Master HamsterKombat Bot][INFO] 2024-08-30 12:37:35 [Account 1] Decoding daily cipher...
[Master HamsterKombat Bot][INFO] 2024-08-30 12:37:35 [Account 1] Daily cipher: HOMIE and Morse code: .... --- -- .. . 
[Master HamsterKombat Bot][INFO] 2024-08-30 12:37:35 [Account 1] Attempting to finish mini game...
`

now stuck almost half an hour on this

**Comment by tboy1337** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/268#issuecomment-2318866602
