### ISSUE TITLE
new game 【Zoopolis】【Gangs Wars】

### ISSUE THREAD

**Issue by zhu18339086032** [masterking32/MasterHamsterKombatBot#280]
add  new game

**Comment by Pawansingh333** [comment]
yes

**Comment by warlomak** [comment]
"c7821fa7-6632-482c-9635-2bd5798585f9": {
        "name": "Gangs Wars",
        "appToken": "b6de60a0-e030-48bb-a551-548372493523",
        "promoId": "c7821fa7-6632-482c-9635-2bd5798585f9",
        "userAgent": "Mozilla/5.0",
        "x-unity-version": None,
        "clientOrigin": "android",
        "clientIdType": "16str",
        "clientVersion": "2.24.0",
        "eventIdType": "timestamp",
        "eventOrigin": "undefined",
        "eventType": "5visitorsChecks",
        "delay": 30,
        "retry_delay": 60,
    },

**Comment by warlomak** [comment]
"b2436c89-e0aa-4aed-8046-9b0515e1c46b": {
        "name": "Zoopolis",
        "appToken": "b2436c89-e0aa-4aed-8046-9b0515e1c46b",
        "promoId": "b2436c89-e0aa-4aed-8046-9b0515e1c46b",
        "userAgent": "Mozilla/5.0",
        "x-unity-version": None,
        "clientOrigin": "android",
        "clientIdType": "16str",
        "clientVersion": "2.24.0",
        "eventIdType": "timestamp",
        "eventOrigin": "undefined",
        "eventType": "5visitorsChecks",
        "delay": 30,
        "retry_delay": 60,
    },

**Comment by tboy1337** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/pull/282
