### ISSUE TITLE
新的问题，这个地方会卡住需要手动回车才可以继续下一步使用

### ISSUE THREAD

**Issue by 284267** [masterking32/MasterHamsterKombatBot#285]
![image](https://github.com/user-attachments/assets/651f4fc8-689c-4fd2-aa5f-bb79e3657ae3)
[Master HamsterKombat Bot][INFO] 2024-08-30 21:05:14 [Account 1] Attempting to buy the best card...
会卡在这个代码地方需要手动回车才可以运行，是什么原因

**Comment by 284267** [comment]
另外一个账号运行时间过长，一直在执行这个任务，时间很漫长如何解决
![image](https://github.com/user-attachments/assets/62c06296-fdf5-4459-8e96-ec236d4268c7)
x'w希望可以解决这个问题

**Comment by masterking32** [comment]
![image](https://github.com/user-attachments/assets/501aff9f-e257-4be1-9c8c-bfa1d6c0531d)
Do not click or select text on the screen, as it will pause the process in the terminal. Simply right-click instead.
