### ISSUE TITLE
Unexpected indent

### ISSUE THREAD

**Issue by qawechi** [masterking32/MasterHamsterKombatBot#287]
![Screenshot_2024-08-30-16-23-26-089_com.deskangel.daremote.jpg](https://github.com/user-attachments/assets/06564365-d1d5-45ae-82ab-585e98c72c20)

**Comment by masterking32** [comment]
It's about your config file, Create a new config file from `config.py.example`, and make sure to use valid values. and don't make unnecessary changes!
