### ISSUE TITLE
mini game cipher incorrect 

### ISSUE THREAD

**Issue by asok00000** [masterking32/MasterHamsterKombatBot#288]
**Describe the bug**
[Master HamsterKombat Bot][INFO] 2024-08-30 22:53:26 [Aniplex] Waiting for 52 seconds, Mini-game Candles will be completed in 52 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-30 22:54:19 [Aniplex] Status code is not 200
[Master HamsterKombat Bot][ERROR] 2024-08-30 22:54:19 [Aniplex] Response: {"error_code":"DAILY_KEYS_MINI_GAME_WRONG","error_message":"DailyKeysMiniGame is wrong MDIzNzA1NTk1NXwxNDU1NDg4MzIzfENhbmRsZXN8MzQ0OTkyMzIwMHxvZm16Z0ZybEdPQlFMVmNzRUlKaDc3MG5OYWdNa2FUQlBEN3NvVWYza1hzPQ=="}
[Master HamsterKombat Bot][ERROR] 2024-08-30 22:54:19 [Aniplex] Unable to claim mini game Candles.

**Comment by masterking32** [comment]
Duplicate AF: https://github.com/masterking32/MasterHamsterKombatBot/issues/268
