### ISSUE TITLE
Add ability to click several cards at a time

### ISSUE THREAD

**Issue by jokaorgua** [masterking32/MasterHamsterKombatBot#29]
Recently I've spotted a situation when 1+ cards can be clicked at a time for the same price (when wait_for_best_card options is enabled)

Example
We have card1 with 1k price and 100 coins (next level will cost 2k and 200 coins), we have card2 with 2k price and 200 coins. And we have an available balance of 10m coins

In current implementation the bot will choose one of the cards, lets say it will be card1, will click it and the card goes to cooldown for 2 hours, after 2 hours the bot will choose one of the cards.

But it will be much faster to click on card1 (cooldown +2 hours) and at the same time click card2 (cooldown for 2 hours) because card2 is the next best card and we can click it right now. so at the same 2 hours we could get more profit

**Comment by supmyhava** [comment]
I just noticed that too, if you could add it that would be great

**Comment by jokaorgua** [comment]
PR https://github.com/masterking32/MasterHamsterKombatBot/pull/48
