### ISSUE TITLE
如何解决这个等待时间问题

### ISSUE THREAD

**Issue by 284267** [masterking32/MasterHamsterKombatBot#295]
![image](https://github.com/user-attachments/assets/10ec204e-565b-435b-9055-0894a60e0bc0)
等待冷却时间过长，如果可以跳过等待冷却时间那会更好，有方法可以实现吗？

**Comment by DineshValor** [comment]
Bro it's an safe procedure, why you become hasty too kuch, let bot do their work smooth and safely.

**Comment by 284267** [comment]
All&nbsp;right!&nbsp;partner

杉树久藏
***@***.***




---原始邮件---
发件人: &quot;Dinesh ***@***.***&gt;
发送时间: 2024年8月31日(周六) 上午9:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [masterking32/MasterHamsterKombatBot] 如何解决这个等待时间问题 (Issue #295)




 
Bro it's an safe procedure, why you become hasty too much, let bot do their work smooth and safely.
 
&mdash;
