### ISSUE TITLE
Add a multi-account via number, please

### ISSUE THREAD

**Issue by cds4r** [masterking32/MasterHamsterKombatBot#300]
Add a multi-account via number, please

**Comment by QualityRU** [comment]
Why complicate the code?

**Comment by DineshValor** [comment]
> Add a multi-account via number, please

With hamster kombat token is easier to handle than login via number!

By the way, could you explain, what issue you facing with token!?

**Comment by masterking32** [comment]
We cannot do that with this project, Cause We only use Auth Token.
