### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by copycatcodex** [masterking32/MasterHamsterKombatBot#302]
hello, I want to ask, here in picture 1 
![1](https://github.com/user-attachments/assets/8c52aebf-734e-40d0-ab18-39dec28c00d9)
 the settings start upgrading at 10,000,000, and stop upgrading at 5000,000, but in picture 2 
![2](https://github.com/user-attachments/assets/e18bda95-e390-4e07-9e0b-458e22671950)
 it explains that my account is still upgrading even though the money doesn't reach 10,000,000, as a result there isn't enough money to upgrade, is there anything wrong? wrong with the settings? or am I the one who doesn't understand? Thank You

**Comment by Fy0urM** [comment]
Read from this https://github.com/masterking32/MasterHamsterKombatBot/blob/main/config.py.example#L76
to wait_for_best_card. this description about wait_for_best_card option

**Comment by copycatcodex** [comment]
so if I set wait_for_best_card: "true", the auto stop and upgrade will be disabled? ?

**Comment by Fy0urM** [comment]
if wait_for_best_card: True, then auto_upgrade_start and auto_upgrade_min options will be ignored and cards will be bought as long as you have a balance.

**Comment by copycatcodex** [comment]
thankss
