### ISSUE TITLE
Socks Proxy Error (http working fine)

### ISSUE THREAD

**Issue by DineshValor** [masterking32/MasterHamsterKombatBot#308]
![Screenshot_20240901-002625](https://github.com/user-attachments/assets/653ca71b-0ea5-49e2-b3ae-635d89fb5ebc)

Also installed `pip install requests[socks]` but still getting error.

![Screenshot_20240901-002830](https://github.com/user-attachments/assets/9d97f544-cf65-491f-b351-d12dacb1c5f3)

Also checked proxy provider side no request ever created or requested for connection. Bot decline even try to connect to proxy via socks, whereas proxy over https working.

**Comment by Endijuan33** [comment]
"https" : "https(or socks5)://user:pass@host:port"
"http" : "http(or socks5)://user:pass@host:port"

I think there should be (") instead of (') and both are inputted with user:pass

**Comment by tboy1337** [comment]
If that doesn't work try changing ```socks5://``` to ```socks5h://```

**Comment by DineshValor** [comment]
> @DineshValor
> 
> _"https"_ : "https(or socks5)://user:pass@host:port" "http" : "http(or socks5)://user:pass@host:port"
> 
> I think there should be (") instead of (') and both are inputted with user:pass

Nope nothing working
```{
"https" : "https(or socks5)://user:pass@host:port",
"http" : "http(or socks5)://user:pass@host:port",
}````

**Comment by DineshValor** [comment]
> If that doesn't work try changing `socks5://` to `socks5h://`

Worked
