### ISSUE TITLE
[Master HamsterKombat Bot][ERROR] [Q1] Error: HTTPSConnectionPool(host='api.hamsterkombat.io', port=443): Max retries exceeded with url: /auth/me-telegram

### ISSUE THREAD

**Issue by odysahe** [masterking32/MasterHamsterKombatBot#31]
![image](https://github.com/user-attachments/assets/de534ad7-928d-4b72-9394-b1fccaf1ff13)

The solution:
Just replace domain ```api.hamsterkombat.io``` to ```api.hamsterkombatgame.io``` in ```main.py```

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/pull/32
