### ISSUE TITLE
Minigames exclusion

### ISSUE THREAD

**Issue by sweetlilmre** [masterking32/MasterHamsterKombatBot#314]
https://github.com/masterking32/MasterHamsterKombatBot/pull/281 notes "Temporarily excluded mini-games from the main loop".
What is  the reason behind this? I'd like to pull to get latest playground games, but don't want to lose mini game functionality.
Is it safe to pull and uncomment the exclusion, or is there a specific reason this code shouldn't be run?

**Comment by Fy0urM** [comment]
the reasons is here
https://github.com/shamhi/HamsterKombatBot/discussions/2272
https://github.com/shamhi/HamsterKombatBot/issues/2268
https://github.com/masterking32/MasterHamsterKombatBot/issues/268

but if you want to try your luck and reskin your accounts, you can uncomment the lines to start mini games in the body of the main loop. 1374-1377
https://github.com/masterking32/MasterHamsterKombatBot/blob/6bd4270b941081d7885b4a2ba22802bd124f27aa/main.py#L1374-L1377

**Comment by sweetlilmre** [comment]
Thank you for the update. I will run with them disabled for now and go and read those links you sent. Have a good Sunday.
