### ISSUE TITLE
Token method doesnt work anymore

### ISSUE THREAD

**Issue by amdjadmoh** [masterking32/MasterHamsterKombatBot#323]
The method of getting the token tn the youtube video doesn't work anymore

**Comment by tboy1337** [comment]
It worked on saturday, I have more accounts to set up so I will check tomorrow

**Comment by amdjadmoh** [comment]
> It worked on saturday, I have more accounts to set up so I will check tomorrow

idk i think they changed something , usually when you launch the bot from web it tells you to play on your phone but now it doesnt , just endless loading
