### ISSUE TITLE
Hexa mini game excluded.

### ISSUE THREAD

**Issue by qawechi** [masterking32/MasterHamsterKombatBot#327]
Guys i cant play hexa minigame. Is it safe right now to use the minigame bot feature?

**Comment by Ashwin3454** [comment]
check now, the hamster team added hexa puzzle again

**Comment by qawechi** [comment]
Oh yeah ur right ..

**Comment by Mihaitafox11** [comment]
Will it be able to play Hexa Puzzle for us? Are you working on that? It would be amazing.

**Comment by AmirhN1382** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/268
