### ISSUE TITLE
not buying

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#329]
yesterday day i have 2.8 profit with 80m coin but now i have 2.8 profit with 130m coin and bot i working but don't buying card for profit
why?

**Comment by iamfraxel** [comment]
Same issue, went from 1 mil to 200 because the bot isnt buying anything

**Comment by copycatcodex** [comment]
check config.js

**Comment by Lastnet0709** [comment]
I just tried it 1 hour ago, almost all features work normally.
Try setting config.py before running the bot

**Comment by AmirhN1382** [comment]
No issue 
![image](https://github.com/user-attachments/assets/0298eab2-8d4e-4c2a-aa04-afe91f3bf523)
This is my current config:
![image](https://github.com/user-attachments/assets/a8facb65-3ce3-408d-8bd2-50213f386587)

The bot is just working fine, check your config.py or copy mine, w/e works the best for you. Closing the issue.
