### ISSUE TITLE
new playground games have been detected

### ISSUE THREAD

**Issue by Endijuan33** [masterking32/MasterHamsterKombatBot#335]
![Screenshot_2024-09-04-14-47-21-723_com termux](https://github.com/user-attachments/assets/995474ed-24aa-498a-aa6a-4dbfdaa81ace)

new playground game: Fluff Crusade. Has anyone found the game ID?

**Comment by Fy0urM** [comment]
> ![Screenshot_2024-09-04-14-47-21-723_com termux](https://github.com/user-attachments/assets/995474ed-24aa-498a-aa6a-4dbfdaa81ace)
> 
> 
> new playground game: Fluff Crusade. Has anyone found the game ID?

In addition to new id's, links for requests have been changed. The bot logic will need to be changed. expect an update.

**Comment by HappyHamster28** [comment]
Tile: e68b39d2-4880-4a31-b3aa-0393e7df10c7
Fluff: 112887b0-a8af-4eb2-ac63-d82df78283d9

**Comment by Endijuan33** [comment]
"?": {
        "name": "fluff crusade",
        "appToken": "?",
        "promoId": "?",
        "userAgent": "UnityPlayer/2022.3.15f1 (UnityWebRequest/1.0, libcurl/8.4.0-DEV)",
        "x-unity-version": "2022.3.15f1",
        "clientOrigin": "?",
        "clientIdType": "32str",
        "clientVersion": "?",
        "eventIdType": "?",
        "eventOrigin": "?",
        "eventType": "?",
        "delay": ?,
        "retry_delay": ?,
    },

actually i need this too 😅

**Comment by Fy0urM** [comment]
> "?": { "name": "fluff crusade", "appToken": "?", "promoId": "?", "userAgent": "UnityPlayer/2022.3.15f1 (UnityWebRequest/1.0, libcurl/8.4.0-DEV)", "x-unity-version": "2022.3.15f1", "clientOrigin": "?", "clientIdType": "32str", "clientVersion": "?", "eventIdType": "?", "eventOrigin": "?", "eventType": "?", "delay": ?, "retry_delay": ?, },
> 
> actually i need this too 😅

you dont need this right now because it is not help, urls are changed, added new request in sequence

**Comment by Rhoniey1011** [comment]
Update game

**Comment by Fy0urM** [comment]
> Update game

Really? You think we should upgrade?
