### ISSUE TITLE
Cant Obtain the Token

### ISSUE THREAD

**Issue by KernelDotDLL** [masterking32/MasterHamsterKombatBot#337]
Did they change the way we could obtain the Bearer token?
Normally it would show that you cant play with pc and you had to login with phone,
but now its Stuck in a loading loop, any ideas?

**Comment by Fy0urM** [comment]
> Did they change the way we could obtain the Bearer token? Normally it would show that you cant play with pc and you had to login with phone, but now its Stuck in a loading loop, any ideas?

indeed, the page takes forever to load, but the link in the iframe is present, take the link from the iframe, change `tgWebAppPlatform=web` to `tgWebAppPlatform=android` and paste the full link with the changed platform into the browser.
