### ISSUE TITLE
a question ⁉️

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#339]
In the games section (getting the keys), a new and strange game has been added that can be entered 8 times and gives coins instead of keys.It is a game in the service of creating keys tile trilo and i don't have this in my account 😕 Is it the same for yours?
(please update the bot for this🙏🏻)

**Comment by Fy0urM** [comment]
tile trio has been added and removed. it is not currently listed as a game.

**Comment by ParsapythonLv** [comment]
> tile trio has been added and removed. it is not currently listed as a game.

ohh thanks bro👍🏻
