### ISSUE TITLE
New Daily and Weekly Task

### ISSUE THREAD

**Issue by MeninSun** [masterking32/MasterHamsterKombatBot#341]
I think there is a new system daily and weekly login, it will make bot can't do other task

![Screenshot_20240905_071121](https://github.com/user-attachments/assets/9f27532e-01a0-4b26-8c01-dbd4b42e8c72)

**Comment by Hzone-glitch** [comment]
That's error: 
[Master HamsterKombat Bot][ERROR] 2024-09-05 03:52:04 [Account 1] Failed to get daily task.

**Comment by Endijuan33** [comment]
i also have the same problem after updating the script

**Comment by MeninSun** [comment]
> i also have the same problem after updating the script

i think not from script, it's from hamster system. (maybe : new url for claiming daily login)

**Comment by XenMe** [comment]
just disable auto_get_daily_task for now, everything else works fine for now.

**Comment by MeninSun** [comment]
I try to make little modification for the script (hope this will help you), and it's work for me
![image](https://github.com/user-attachments/assets/2eb07213-1df8-42da-9b84-ce80fa8365d0)
![image](https://github.com/user-attachments/assets/56a49bbd-7f02-4831-bc40-64778708cb49)

but i forget to distinguish the reward between key or coins, still waiting for the repo owner to update it.

**Comment by AmirhN1382** [comment]
Update the bot.

**Comment by MeninSun** [comment]
> Update the bot.

Perfect!
