### ISSUE TITLE
Update issue of Hamster Sign-in

### ISSUE THREAD

**Issue by 284267** [masterking32/MasterHamsterKombatBot#345]
Today, the hamster sign-in method has been updated. Will this affect the operation of the code, or should I ignore it as usual?

**Comment by Fy0urM** [comment]
what do you mean by sign-in method?

**Comment by 284267** [comment]
The most authoritative question is that the hamster's sign-in seems to have been updated. Will this affect the operation of the code?

**Comment by 284267** [comment]
It means "Sign in updated". The translation here is wrong.

**Comment by 284267** [comment]
The daily check-in has been updated, not the login method. There is an error in the translation.

**Comment by Fy0urM** [comment]
> The daily check-in has been updated, not the login method. There is an error in the translation.

task updates including daily tasks have been added to the bot within the last hour. update the bot

**Comment by ahmedibrahimsaadmostafa** [comment]
I changed the "streak_days" to "streak_days_special"
And then it worked well.

**Comment by 284267** [comment]
I&nbsp;clone&nbsp;the&nbsp;project&nbsp;and&nbsp;reconfigure&nbsp;it&nbsp;directly,&nbsp;which&nbsp;I&nbsp;think&nbsp;is&nbsp;more&nbsp;intuitive&nbsp;and&nbsp;simple.

杉树久藏
***@***.***




---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 10:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [masterking32/MasterHamsterKombatBot] Update issue of HamsterSign-in (Issue #345)




 
I changed the "streak_days" to "streak_days_special"
 And then it worked well.
 
&mdash;

**Comment by Fy0urM** [comment]
> I&nbsp;clone&nbsp;the&nbsp;project&nbsp;and&nbsp;reconfigure&nbsp;it&nbsp;directly,&nbsp;which&nbsp;I&nbsp;think&nbsp;is&nbsp;more&nbsp;intuitive&nbsp;and&nbsp;simple. 杉树久藏 ***@***.***


thanks to the replies from e-mail))

**Comment by 284267** [comment]
config.py文件没有更新吧，我配置项目以后只复制粘贴了这个文件以前的配置代码，这没有我问题吧.

**Comment by Ashwin3454** [comment]
> I changed the "streak_days" to "streak_days_special" And then it worked well.

can u make a PR if its working ?

**Comment by 284267** [comment]
Is&nbsp;it&nbsp;just&nbsp;to&nbsp;change&nbsp;this&nbsp;code?&nbsp;I&nbsp;don't&nbsp;know&nbsp;what&nbsp;the&nbsp;function&nbsp;of&nbsp;this&nbsp;part&nbsp;of&nbsp;the&nbsp;code&nbsp;is.&nbsp;I&nbsp;have&nbsp;cloned&nbsp;the&nbsp;configuration&nbsp;project&nbsp;again,&nbsp;because&nbsp;I&nbsp;don't&nbsp;quite&nbsp;understand&nbsp;where&nbsp;it&nbsp;has&nbsp;been&nbsp;updated.

杉树久藏
***@***.***




---Original---
From: &quot;Ashwin ***@***.***&gt;
Date: Thu, Sep 5, 2024 13:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [masterking32/MasterHamsterKombatBot] Update issue of HamsterSign-in (Issue #345)




  
I changed the "streak_days" to "streak_days_special" And then it worked well.
  
can u make a PR if its working ?
 
&mdash;

**Comment by Fy0urM** [comment]
> > I changed the "streak_days" to "streak_days_special" And then it worked well.
> 
> can u make a PR if its working ?

Stop panicking, see commits and other topics.
https://github.com/masterking32/MasterHamsterKombatBot/commits/main/
https://github.com/masterking32/MasterHamsterKombatBot/issues/343
https://github.com/masterking32/MasterHamsterKombatBot/issues/341
https://github.com/masterking32/MasterHamsterKombatBot/pull/342

**Comment by 284267** [comment]
Can&nbsp;this&nbsp;code&nbsp;still&nbsp;complete&nbsp;the&nbsp;inviter&nbsp;task&nbsp;by&nbsp;itself?&nbsp;I'm&nbsp;Xiao&nbsp;Bai&nbsp;and&nbsp;I&nbsp;don't&nbsp;understand&nbsp;it.&nbsp;Thank&nbsp;you&nbsp;for&nbsp;your&nbsp;answer.

杉树久藏
***@***.***




---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 13:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [masterking32/MasterHamsterKombatBot] Update issue of HamsterSign-in (Issue #345)




   
I changed the "streak_days" to "streak_days_special" And then it worked well.
  
can u make a PR if its working ?
  
Stop panicking, see commits and other topics.
 https://github.com/masterking32/MasterHamsterKombatBot/commits/main/
 #343
 #341
 #342
 
&mdash;

**Comment by Fy0urM** [comment]
> Can&nbsp;this&nbsp;code&nbsp;still&nbsp;complete&nbsp;the&nbsp;inviter&nbsp;task&nbsp;by&nbsp;itself?&nbsp;I'm&nbsp;Xiao&nbsp;Bai&nbsp;and&nbsp;I&nbsp;don't&nbsp;understand&nbsp;it.&nbsp;Thank&nbsp;you&nbsp;for&nbsp;your&nbsp;answer.

If you think that it is safe to perform the task of inviting friends without having the required number of friends, it can be realized. Otherwise, you need to refine the logic and make additional checks. This is not a priority task at the moment.

**Comment by 284267** [comment]
All&nbsp;right!&nbsp;Thank&nbsp;you&nbsp;for&nbsp;your&nbsp;answer.&nbsp;Wish&nbsp;you&nbsp;a&nbsp;happy&nbsp;life!

杉树久藏
***@***.***




---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 13:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [masterking32/MasterHamsterKombatBot] Update issue of HamsterSign-in (Issue #345)




  
Can this code still complete the inviter task by itself? I'm Xiao Bai and I don't understand it. Thank you for your answer.
  
If you think that it is safe to perform the task of inviting friends without having the required number of friends, it can be realized. Otherwise, you need to refine the logic and make additional checks. This is not a priority task at the moment.
 
&mdash;
