### ISSUE TITLE
Error receiving key 

### ISSUE THREAD

**Issue by Homavi88** [masterking32/MasterHamsterKombatBot#347]
Hi 
A bid delay appeared for key. Is this normal ? 

`Event registration for Mow and Trim was successful, but no code was provided, retry in 63 seconds`

thk

**Comment by Fy0urM** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/344

**Comment by Ashwin3454** [comment]
![Screenshot 2024-09-05 102725](https://github.com/user-attachments/assets/940915e8-6816-4dc3-a4f3-b351596ba779)

**Comment by Fy0urM** [comment]
> ![Screenshot 2024-09-05 102725](https://github.com/user-attachments/assets/940915e8-6816-4dc3-a4f3-b351596ba779)
> 

Read my prev comment
