### ISSUE TITLE
"No code provided" error

### ISSUE THREAD

**Issue by epis78** [masterking32/MasterHamsterKombatBot#349]
Hi

today, i am repeatedly getting the below error for various games:

- Event registration for Polysphere was successful, but no code was provided, retry in 25 seconds
- Event registration for Zoopolis was successful, but no code was provided, retry in 47 seconds.
- Event registration for Twerk Race was successful, but no code was provided, retry in 24 seconds.
- Event registration for Chain Cube 2048 was successful, but no code was provided, retry in 24 seconds

it will continue to retry (i've seen up to 15 retries) until the issue resolves, and then happens for another game.

has it happened to anybody else?

**Comment by QuiglyGames** [comment]
![1](https://github.com/user-attachments/assets/bb7d10ef-e3af-44ae-8181-9571952cd784)

I also write to the log, but after 4-6 attempts, the code is applied to the game.

**Comment by zclsx** [comment]
token update now， only supply mobile

**Comment by Fy0urM** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/344
