### ISSUE TITLE
Minigame : Puzzle

### ISSUE THREAD

**Issue by MeninSun** [masterking32/MasterHamsterKombatBot#350]
I just wanna ask, is everyone face the same problem in puzzle game (not do the task and not acquire the key)?

**Comment by Fy0urM** [comment]
> I just wanna ask, is everyone face the same problem in puzzle game (not do the task and not acquire the key)?

By bot or by yourself?

**Comment by MeninSun** [comment]
> > I just wanna ask, is everyone face the same problem in puzzle game (not do the task and not acquire the key)?
> 
> By bot or by yourself?

by bot, please let me know if you all got the key, maybe i make a mistake/miss configuration.

**Comment by Fy0urM** [comment]
> > > I just wanna ask, is everyone face the same problem in puzzle game (not do the task and not acquire the key)?
> > 
> > By bot or by yourself?
> 
> by bot, please let me know if you all got the key, maybe i make a mistake/miss configuration.


In the bot, autocompletion of mini games has been disabled for security reasons. The available cipher generation is not trustworthy. If you want to risk your account you can uncomment a few lines in the main bot loop

**Comment by MeninSun** [comment]
> > > > I just wanna ask, is everyone face the same problem in puzzle game (not do the task and not acquire the key)?
> > > 
> > > 
> > > By bot or by yourself?
> > 
> > 
> > by bot, please let me know if you all got the key, maybe i make a mistake/miss configuration.
> 
> In the bot, autocompletion of mini games has been disabled for security reasons. The available cipher generation is not trustworthy. If you want to risk your account you can uncomment a few lines in the main bot loop

Ah, i got it! Thank you!
