### ISSUE TITLE
New playground game: Stone Age

### ISSUE THREAD

**Issue by Fy0urM** [masterking32/MasterHamsterKombatBot#351]
Interesting situation, on the main Lorde account there is a new game, but on the test account Platinum it is not. Does anyone else have a similar situation?

![image](https://github.com/user-attachments/assets/a57d8b1d-227a-4a33-8654-e8f4ab03d014)
![image](https://github.com/user-attachments/assets/ff15da27-ef8a-47d4-9b5e-cae01eccfe51)

**Comment by Ashwin3454** [comment]
Yes, I'm experiencing the same issue. In some of my accounts, the new game isn't appearing.

**Comment by miladesign** [comment]
i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)

**Comment by Fy0urM** [comment]
> i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)

congratulations

**Comment by autoattack999** [comment]
> i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)

this tile tiro or stone age?

**Comment by miladesign** [comment]
> > i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)
> 
> this tile tiro or stone age?

stone age:
```
"appToken": "04ebd6de-69b7-43d1-9c4b-04a6ca3305af"
"promoId": "04ebd6de-69b7-43d1-9c4b-04a6ca3305af"
```

tile trio:
```
"appToken": "e68b39d2-4880-4a31-b3aa-0393e7df10c7"
"promoId": "e68b39d2-4880-4a31-b3aa-0393e7df10c7"
```

**Comment by Fy0urM** [comment]
That is, no one is not embarrassed that the game on some accounts appeared and on others not, I understand correctly?

**Comment by miladesign** [comment]
> That is, no one is not embarrassed that the game on some accounts appeared and on others not, I understand correctly?

yea. i have some accounts and its only in one of them

**Comment by ParsapythonLv** [comment]
![Screenshot_2024-09-05-18-48-40-396_ir ilmili telegraph](https://github.com/user-attachments/assets/cfc04c59-f822-4462-baac-df7bcc4a6462)
i have this, hamster is getting buggy 😂😂😂 , tile trio really not deleted and when you can't see it in games when you reedem the promo of this game will you get the key , maybe its like tile trilo and It does not exist in appearance, but it actually exists

**Comment by Fy0urM** [comment]
> > That is, no one is not embarrassed that the game on some accounts appeared and on others not, I understand correctly?
> 
> yea. i have some accounts and its only in one of them

And it doesn't bother you in any way that you immediately updated the config manually and send incorrect data to the server?

**Comment by Fy0urM** [comment]
> ![Screenshot_2024-09-05-18-48-40-396_ir ilmili telegraph](https://github.com/user-attachments/assets/cfc04c59-f822-4462-baac-df7bcc4a6462)
> i have this, hamster is getting buggy 😂😂😂 , tile trio really not deleted and when you can't see it in games when you reedem the promo of this game will you get the key , maybe its like tile trilo and It does not exist in appearance, but it actually exists

Tile trio returned to the game list a few hours ago

**Comment by miladesign** [comment]
> > > That is, no one is not embarrassed that the game on some accounts appeared and on others not, I understand correctly?
> > 
> > 
> > yea. i have some accounts and its only in one of them
> 
> And it doesn't bother you in any way that you immediately updated the config manually and send incorrect data to the server?

no really 😆 i will update config as soon as i get right config

**Comment by Fy0urM** [comment]
I doubt that it is a bug, in the responses from the server for one account is the game for one account and for the other is not

**Comment by Fy0urM** [comment]
> i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)

How u get code without update the config?)

**Comment by miladesign** [comment]
> > i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)
> 
> How u get code without update the config?)

i made this site to get codes
https://miladesign.ir/hamstergame/

**Comment by Fy0urM** [comment]
> > > i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)
> > 
> > How u get code without update the config?)
> 
> i made this site to get codes
> https://miladesign.ir/hamstergame/

 I got it

**Comment by Fy0urM** [comment]
> but still you can redeem it even if its not in get-promos

Yes, but how safe is it for the account?

**Comment by autoattack999** [comment]
> > > i got keys with tile trio config (just used `04ebd6de-69b7-43d1-9c4b-04a6ca3305af` as promoId and appToken)
> > 
> > 
> > this tile tiro or stone age?
> 
> stone age:
> 
> ```
> "appToken": "04ebd6de-69b7-43d1-9c4b-04a6ca3305af"
> "promoId": "04ebd6de-69b7-43d1-9c4b-04a6ca3305af"
> ```
> 
> tile trio:
> 
> ```
> "appToken": "e68b39d2-4880-4a31-b3aa-0393e7df10c7"
> "promoId": "e68b39d2-4880-4a31-b3aa-0393e7df10c7"
> ```

thank you very much, can you tell me how to get apptoken / promoid? i really want to learn..

**Comment by miladesign** [comment]
> > but still you can redeem it even if its not in get-promos
> 
> Yes, but how safe is it for the account?

i dont know about that.
also i noticed that you are sending all taps at same time (also for boost tap) its impossible to tap all available taps with one request.
my bot is in php language. i wrote it like you tap with 5 fingers and have random ticks and sleep.
this is my code. maybe you can use it
```
if ($this->account['autoTap']) {
  // Tap
  $tapFinished = false;
  $retryCount = 3;
  $tapsCount = 0;
  $totalTaps = 0;
  $sentTaps = 0;
  while(true) {
      $delay = $this->getRandomDelay();
      sleep($delay);
      if (($availableTaps + $sentTaps) < $maxTaps) {
          $availableTaps += $sentTaps;
      } else {
          $availableTaps = $maxTaps;
      }
      $calculatedTaps = $this->calculateTaps($earnPerTap, $fingers, $delay);
      if ($availableTaps <= $calculatedTaps) {
          $calculatedTaps = $availableTaps;
          $tapFinished = true;
      }
      
      $sendTaps = (int)($calculatedTaps / $earnPerTap);
      $sentAvailableTaps = ($availableTaps - $calculatedTaps) + $delay;
      $tapResponse = $this->tap($sendTaps, $sentAvailableTaps);
      if ($tapResponse['success']) {
          $totalTaps += $sendTaps;
          $sentTaps = $sendTaps;
          $availableTaps = $tapResponse['response']['clickerUser']['availableTaps'];
          $maxTaps = $tapResponse['response']['clickerUser']['maxTaps'];
          $this->updateBotResult($tapResponse);

          $tapsCount += 1;
          if ($tapFinished) {
              $this->setResult('tap', 'success', true);
              $this->setResult('tap', 'total', $totalTaps);
              $this->setResult('tap', 'count', $tapsCount);   
              break;
          }
      } else {
          $retryCount -= 1;
          if ($retryCount < 0) {
              $this->setResult('tap', 'success', false);
              $this->setResult('tap', 'message', $tapResponse["response"]['error_message'] ?? "خطای ناشناخته");
              break;
          }
      }
  }
}
```

**Comment by Fy0urM** [comment]
> i dont know about that.
> also i noticed that you are sending all taps at same time (also for boost tap) its impossible to tap all available taps with one request.
> my bot is in php language. i wrote it like you tap with 5 fingers and have random ticks and sleep.
> this is my code. maybe you can use it

about taps. yes, it's impossible. but apparently you don't know how it works. in a real game while you tap no requests are sent, taps are counted locally and as soon as you stop tapping a request is sent to the server with the number of taps.

**Comment by Fy0urM** [comment]
The only thing is, it might be worth doing a delay between starting tap emulation and sending taps and between buying taps and sending taps

**Comment by Fy0urM** [comment]
> thank you very much, can you tell me how to get apptoken / promoid? i really want to learn..

If you don't know how to do it, you don't know how to use it properly and you don't need it.

**Comment by miladesign** [comment]
yes i know about that. but its take more than 2min to send 12k taps. i tried to tap manually while i was debuging and i found out that its send some of taps even when i was tapping. and its take time to finish it. so i used method to give me random second between 45-75. calculated how many taps with 5 finger can do in that time. waited that time and send it. repeat it until no available taps

**Comment by miladesign** [comment]
also while you tapping the available taps can recover some (3 per second for now) so i add them too

**Comment by autoattack999** [comment]
> > thank you very much, can you tell me how to get apptoken / promoid? i really want to learn..
> 
> If you don't know how to do it, you don't know how to use it properly and you don't need it.

:(

**Comment by Fy0urM** [comment]
Well, I collected all the necessary data and made the changes. but I don't have a test account that has the game on it so I can test the changes. all my 4 test accounts don't have the new game.

**Comment by Fy0urM** [comment]
> :(

I'm sorry, I didn't mean to offend you. I'm just saying that for your own safety.

**Comment by Fy0urM** [comment]
> yes i know about that. but its take more than 2min to send 12k taps. i tried to tap manually while i was debuging and i found out that its send some of taps even when i was tapping. and its take time to finish it. so i used method to give me random second between 45-75. calculated how many taps with 5 finger can do in that time. waited that time and send it. repeat it until no available taps

I understand what you mean, maybe I or the author will make adjustments in the future. and about 12k tap. they are 12k, but 12k is not tap but energy, and each tap costs a certain amount of energy.

**Comment by miladesign** [comment]
> > yes i know about that. but its take more than 2min to send 12k taps. i tried to tap manually while i was debuging and i found out that its send some of taps even when i was tapping. and its take time to finish it. so i used method to give me random second between 45-75. calculated how many taps with 5 finger can do in that time. waited that time and send it. repeat it until no available taps
> 
> I understand what you mean, maybe I or the author will make adjustments in the future. and about 12k tap. they are 12k, but 12k is not tap but energy, and each tap costs a certain amount of energy.

yea i calculated that earnPerTap too. you can see in here i do this:
`$calculatedTaps = $this->calculateTaps($earnPerTap, $fingers, $delay);`
```
function calculateTaps($earnPerTap, $fingers, $delay) {
  return $earnPerTap * $fingers * $delay;
}
```

i used all i can do to make it like real playing

**Comment by Fy0urM** [comment]
update already on my branch, but use it on your own risk
https://github.com/masterking32/MasterHamsterKombatBot/pull/354

**Comment by Fy0urM** [comment]
I polled a few people I know, some of them have it, some of them don't, regardless of using bots or keys from generators and account level. hopefully it's just a bug.

**Comment by Fy0urM** [comment]
the game showed up on one of the test accounts.

**Comment by epis78** [comment]
the same here. i have it in one account but not the other.
