### ISSUE TITLE
Why here?

### ISSUE THREAD

**Issue by autoattack999** [masterking32/MasterHamsterKombatBot#356]
CLOSED

**Comment by Fy0urM** [comment]
> Help me...

https://github.com/masterking32/MasterHamsterKombatBot/issues/344#issuecomment-2330434919

**Comment by autoattack999** [comment]
> > Help me...
> 
> [#344 (comment)](https://github.com/masterking32/MasterHamsterKombatBot/issues/344#issuecomment-2330434919)

Oke thankyouuuu

**Comment by autoattack999** [comment]
thankyou
