### ISSUE TITLE
new game detected : Stone Age

### ISSUE THREAD

**Issue by Endijuan33** [masterking32/MasterHamsterKombatBot#357]
![Screenshot_2024-09-06-00-46-27-802_org telegram messenger](https://github.com/user-attachments/assets/bbe82266-d41c-4042-a14d-0688d6ce6089)
Lately it seems like hamster developers are busy adding new games to playground. I hope the script will be updated soon too.

**Comment by Ashwin3454** [comment]
#354

**Comment by AmirhN1382** [comment]
Update the bot.
