### ISSUE TITLE
adding this game

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#358]
adding stone age please
```10: {
        'name': 'Stone Age',
        'appToken': '04ebd6de-69b7-43d1-9c4b-04a6ca3305af',
        'promoId': '04ebd6de-69b7-43d1-9c4b-04a6ca3305af',
        'timing': 20000 / 1000,
        'attempts': 20,
    },
}

**Comment by Ashwin3454** [comment]
> adding stone age please
> 
> ```
>         'name': 'Stone Age',
>         'appToken': '04ebd6de-69b7-43d1-9c4b-04a6ca3305af',
>         'promoId': '04ebd6de-69b7-43d1-9c4b-04a6ca3305af',
>         'timing': 20000 / 1000,
>         'attempts': 20,
>     },
> }
> ```

#354

**Comment by AmirhN1382** [comment]
Update the bot.
