### ISSUE TITLE
Unable to obtain Token

### ISSUE THREAD

**Issue by Praveensenpai** [masterking32/MasterHamsterKombatBot#364]
even after doing tgWebAppPlatform=web to tgWebAppPlatform=android

it still shows Play on your mobile

**Comment by Fy0urM** [comment]
> even after doing tgWebAppPlatform=web to tgWebAppPlatform=android
> 
> it still shows Play on your mobile
> 
> 

Check if '/' exists between .com and #...

**Comment by Praveensenpai** [comment]
![{4AB8E3C2-BDB6-4DC3-AD6D-3DB29C77362E}](https://github.com/user-attachments/assets/75f8e7f7-0153-4053-b608-247bbef2d1fb)

**Comment by Fy0urM** [comment]
> ![{4AB8E3C2-BDB6-4DC3-AD6D-3DB29C77362E}](https://private-user-images.githubusercontent.com/71966071/365059167-75f8e7f7-0153-4053-b608-247bbef2d1fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDQ5MzcsIm5iZiI6MTcyNTYwNDYzNywicGF0aCI6Ii83MTk2NjA3MS8zNjUwNTkxNjctNzVmOGU3ZjctMDE1My00MDUzLWI2MDgtMjQ3YmJlZjJkMWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA2MzcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYTg5MTFmZWNhYjM5OGE1Y2VjM2FjYWU3NDg4MzU4NTMxNjE1ZjAyN2Y3MjRjZmJlZGI2ZTk3ZjA0MzYwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8lIuu334OHdX7FVq2fZrhwml7BNEJsxzPdAJiifXEls)

then I'm sorry, I don't know what else to try.

**Comment by Praveensenpai** [comment]
I figured it. my bad

after doing tgWebAppPlatform=weba to tgWebAppPlatform=android
it works

it was weba not web

**Comment by sarqovik** [comment]
![hamster](https://github.com/user-attachments/assets/d92fc41f-958a-415f-b0c4-b3927b2c0e45)
how to fix it? thanks

**Comment by copycatcodex** [comment]
token auth?

**Comment by copycatcodex** [comment]
> ![hamster](https://private-user-images.githubusercontent.com/42547245/365088902-d92fc41f-958a-415f-b0c4-b3927b2c0e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTk2MjksIm5iZiI6MTcyNTYxOTMyOSwicGF0aCI6Ii80MjU0NzI0NS8zNjUwODg5MDItZDkyZmM0MWYtOTU4YS00MTVmLWIwYzQtYjM5MjdiMmMwZTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEwNDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlN2ZmMGEwMTkwYzc1MTdhMjllNjI5MzQ1NThhMGJlOWNiOGI2ODdlYjMzY2RjM2Q3ZThjMzVmZDhkM2MyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vhmogayauM9irESXtWjVGuSS8JvOR-oqAQz6mVc_SVM) how to fix it? thanks

I think something is wrong with your proxy sir.

**Comment by sarqovik** [comment]
> > ![hamster](https://private-user-images.githubusercontent.com/42547245/365088902-d92fc41f-958a-415f-b0c4-b3927b2c0e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTk2MjksIm5iZiI6MTcyNTYxOTMyOSwicGF0aCI6Ii80MjU0NzI0NS8zNjUwODg5MDItZDkyZmM0MWYtOTU4YS00MTVmLWIwYzQtYjM5MjdiMmMwZTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEwNDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlN2ZmMGEwMTkwYzc1MTdhMjllNjI5MzQ1NThhMGJlOWNiOGI2ODdlYjMzY2RjM2Q3ZThjMzVmZDhkM2MyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vhmogayauM9irESXtWjVGuSS8JvOR-oqAQz6mVc_SVM) how to fix it? thanks
> 
> I think something is wrong with your proxy sir.

ok sir, thank u
