### ISSUE TITLE
Status code is not 200

### ISSUE THREAD

**Issue by camillo1991** [masterking32/MasterHamsterKombatBot#366]
Hello! How to fix  [Account 1] Status code is not 200?

[Master HamsterKombat Bot][ERROR] 2024-09-06 15:15:15 [Account 1] Status code is not 200
[Master HamsterKombat Bot][ERROR] 2024-09-06 15:15:15 [Account 1] Response: Internal server error
[Master HamsterKombat Bot][ERROR] 2024-09-06 15:15:15 [Account 1] Failed to buy an upgrade.
[Master HamsterKombat Bot][ERROR] 2024-09-06 15:15:15 Sleeping for 154 seconds because of random delay...
[Master HamsterKombat Bot][ERROR] 2024-09-06 15:15:15 Rechecking all accounts in 11000 seconds...

Proxy 100% work and support https

**Comment by camillo1991** [comment]
Before this error, there was a log like this:
 Attempting to buy an upgrade...

**Comment by camillo1991** [comment]
Or maybe it's a problem with the Hamster Kombat servers? Because I couldn't get into the app this afternoon.

**Comment by Fy0urM** [comment]
> Response: Internal server error

this is your answer

**Comment by qawechi** [comment]
Does this bearer token have anything to do with telegram sessions? Because i terminated all the sessions and the bot is still working ..
