### ISSUE TITLE
Is there a way to check for new Bearer token automatically? They started changing them and assigning cheating achievements.

### ISSUE THREAD

**Issue by vashamamasha2014** [masterking32/MasterHamsterKombatBot#370]
Is there a way to check for new Bearer token automatically? They started changing them and assigning cheating achievements.

**Comment by AmirhN1382** [comment]
The achievement has nothing to do with the Bearer token tho, but maybe automatically changing it might be a good idea.

**Comment by vashamamasha2014** [comment]
> The achievement has nothing to do with the Bearer token tho, but maybe automatically changing it might be a good idea.

Too suspicious, old tokens started to change, warnings about blocking started to arrive. These achievements did not arrive on my new fresh accounts (2-3 days) with a bot.

**Comment by Emperor-One** [comment]
It is highly likely that they are giving people these achievements for multiple accounts. I suspect the achievements were given for accounts that share a local storage and cookies because mini apps are just websites after all. And, if you have more than one telegram account on one device, and start Hamster Kombat, they can easily detect this...

**Comment by 284267** [comment]
"auto_finish_mini_game": False, # Enable auto finish mini game by setting it to True, or set it to False to disable
Does anyone have any good suggestions on this? Is this as likely to get an account banned as # "auto_playground_games": True, # Enable auto playground games by setting it to True

**Comment by miladesign** [comment]
> Is there a way to check for new Bearer token automatically? They started changing them and assigning cheating achievements.

you need telegram api token to do this. from here
https://my.telegram.org/
