### ISSUE TITLE
Can't execute these, the code is correct

### ISSUE THREAD

**Issue by 284267** [masterking32/MasterHamsterKombatBot#371]
![image](https://github.com/user-attachments/assets/12f739a7-0d4e-4e17-813c-3bd277149493)
Can't execute these, the code is correct："auto_get_task": True,

**Comment by Fy0urM** [comment]
it's excluded, if you want, you can find and edit this here https://github.com/masterking32/MasterHamsterKombatBot/blob/609e982b4ed9e1ea3abb103fa8b31237c3bada8a/main.py#L1708
```python
task["id"] not in ["subscribe_hk_facebook",
                   "subscribe_hk_instagram",
                   "subscribe_telegram_cryptofam",
                   "subscribe_telegram_channel",
                   "subscribe_x_account", 
                   "select_exchange", 
                   "invite_friends",
                   "streak_days_special"]
```
is an array of exceptions, from top to bottom, like the tasks in the screenshot, except for the last task streak_days_special, this is a dayli task that is handled elsewhere and added to avoid repetition

**Comment by 284267** [comment]
It was working fine originally. Why is the updated code excluded?

**Comment by Fy0urM** [comment]
> It was working fine originally. Why is the updated code excluded?

Because the last time the task api response will updated, I wasn't sure which tasks were executing before the update and decided to exclude all but the periodic youtube tasks. I'll fix this in the next PR

**Comment by 284267** [comment]
I see that the latest updated function is that 5 million card combinations can be completed every day through API. I wonder if this new function will be blocked?
