### ISSUE TITLE
New Issues??

### ISSUE THREAD

**Issue by copycatcodex** [masterking32/MasterHamsterKombatBot#374]
I updated it earlier, and it went smoothly until the combo ran normally (couldn't take it because the card was locked)
![image](https://github.com/user-attachments/assets/4a449a4e-0b0e-4e95-93da-2e8e22223a6b)
it seems like this error occurs when the daily combo changes. 🤔🤔
what do you think?

**Comment by Fy0urM** [comment]
thats my bad, i already make new PR with fixes

**Comment by 284267** [comment]
> 那是我的错，我已经做了新的带有修复的 PR

I also have the same problem, which occurs several times overnight. Do I need to update the code? If the command is executed to update the code, will the file parameters I set in config.py change?

**Comment by Fy0urM** [comment]
> I also have the same problem, which occurs several times overnight. Do I need to update the code? If the command is executed to update the code, will the file parameters I set in config.py change?

Yes, you need to update the bot. no, config.py will not change when you update the bot even via git clone or git pull
