### ISSUE TITLE
How to modify the click frequency or clicks per second

### ISSUE THREAD

**Issue by jamesblunt** [masterking32/MasterHamsterKombatBot#375]
How to modify the click frequency or clicks per second

**Comment by copycatcodex** [comment]
which click?

**Comment by jamesblunt** [comment]
> which click?

It is the frequency of tapping. I have seen some people receive cheating warnings because they used a program to set 10,000 taps per second.

**Comment by copycatcodex** [comment]
![image](https://github.com/user-attachments/assets/3d2736bd-e5c6-4568-bdad-a3bac5d234b4)
It seems like this is a Tap function, but I have no idea how to change the timestamp part. I think the author has given a safe setting.

**Comment by jamesblunt** [comment]
ok,thx very much
