### ISSUE TITLE
Как узнать свой Authorization Bearer Token?

### ISSUE THREAD

**Issue by pashva11** [masterking32/MasterHamsterKombatBot#38]
Здравствуйте.
Подскажите, как получить Authorization Bearer Token?
Инструкция из видео не работает. При запуске Hamster Combat в браузере появляется QR-код и нет данных об Authorization Bearer Token. Как можно узнать свой Authorization Bearer Token?

**Comment by masterking32** [comment]
Hello,
I tested it, and it looks fine and works very well. Please try the latest version and ensure you're doing everything correctly; maybe you did something wrong. I checked, and it works fine.

**Comment by pashva11** [comment]
Да, ты прав - я попробовал сегодня и сегодня всё получилось не знаю, почему вчера не получалось! Спасибо - буду сегодня дальше пробовать запустить твою программу)))

Скажи, а можно сделать всё проще, чтобы я просто в текстовый файл вставил свои параметры Authorization Bearer и UserAgent, а ты сам их уже подставлял в код, куда нужно? А я бы просто запускал один файл какой-нибудь .exe или .bat или ещё какой-нибудь? Я сам не программист и выполнять все шаги, которые описаны в инструкции мне довольно сложно. Легче с видео-инструкцией, но т.к. вид кода всё время меняется (сейчас добавилось несколько аккаунтов и код уже визуально изменился), то мне сложно понять, в правильное место я вставляю свои данные или нет?...
