### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by cagdasb** [masterking32/MasterHamsterKombatBot#393]
It was working for about 10 hours. Now I realized it stoped because of this

Traceback (most recent call last):
  File "/home/x/MasterHamsterKombatBot/main.py", line 1913, in <module>
    main()
  File "/home/x/MasterHamsterKombatBot/main.py", line 1907, in main
    asyncio.run(RunAccounts())
  File "/home/x/MasterHamsterKombatBot/main.py", line 1874, in RunAccounts
    account.Start()
  File "/home/x/MasterHamsterKombatBot/main.py", line 1734, in Start
    self.ClaimDailyCombo()
  File "/home/x/MasterHamsterKombatBot/main.py", line 586, in ClaimDailyCombo
    isClaimed = buyResult.get("dailyCombo", {}).get("isClaimed", False)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Fy0urM** [comment]
> It was working for about 10 hours. Now I realized it stoped because of this
> 
> 
> Traceback (most recent call last):
>   File "/home/x/MasterHamsterKombatBot/main.py", line 1913, in <module>
>     main()
>   File "/home/x/MasterHamsterKombatBot/main.py", line 1907, in main
>     asyncio.run(RunAccounts())
>   File "/home/x/MasterHamsterKombatBot/main.py", line 1874, in RunAccounts
>     account.Start()
>   File "/home/x/MasterHamsterKombatBot/main.py", line 1734, in Start
>     self.ClaimDailyCombo()
>   File "/home/x/MasterHamsterKombatBot/main.py", line 586, in ClaimDailyCombo
>     isClaimed = buyResult.get("dailyCombo", {}).get("isClaimed", False)
> AttributeError: 'NoneType' object has no attribute 'get'
> 

Update to the last version

**Comment by cagdasb** [comment]
Checking for daily combo...

**Comment by cagdasb** [comment]
> > It was working for about 10 hours. Now I realized it stoped because of this
> > Traceback (most recent call last):
> > File "/home/x/MasterHamsterKombatBot/main.py", line 1913, in 
> > main()
> > File "/home/x/MasterHamsterKombatBot/main.py", line 1907, in main
> > asyncio.run(RunAccounts())
> > File "/home/x/MasterHamsterKombatBot/main.py", line 1874, in RunAccounts
> > account.Start()
> > File "/home/x/MasterHamsterKombatBot/main.py", line 1734, in Start
> > self.ClaimDailyCombo()
> > File "/home/x/MasterHamsterKombatBot/main.py", line 586, in ClaimDailyCombo
> > isClaimed = buyResult.get("dailyCombo", {}).get("isClaimed", False)
> > AttributeError: 'NoneType' object has no attribute 'get'
> 
> Update to the last version

It's the latest version.

**Comment by Fy0urM** [comment]
> It's the latest version.

Are you sure? Last modified about 3 hours ago.

**Comment by Fy0urM** [comment]
The latest update includes exception handling when executing the method responsible for daily combo and the script should not be interrupted

**Comment by cagdasb** [comment]
> The latest update includes exception handling when executing the method responsible for daily combo and the script should not be interrupted

Just checked that "modified about 3 hours ago". Mine is not latest version yes.
Going to take care of it in few hours then close that issue. 
Thanks
