### ISSUE TITLE
Proxy Reconnect Issue

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#400]
I woke up at 9am and checked the bot and found it stuck with the error `[MasterHamsterKombatBot] [2024-09-10 04:05:09] [ERROR] [Account 10]: ✖ Error: HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/1/login-client (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))`

I know its because of my proxy but the proxy came back up not long later and the bot doesn’t try to connect again so just stays stuck until I manually restart it.

**Comment by vanhieu1509** [comment]
[Unable to connect to proxy] => check your proxy service

**Comment by masterking32** [comment]
You can use good proxies.

**Comment by tboy1337** [comment]
@masterking32 im using [Webshare](https://www.webshare.io) as you recommended so im using "good proxies".  I checked again today and again I found 2 bots closed on their own.
