### ISSUE TITLE
Script does not buy card

### ISSUE THREAD

**Issue by Homavi88** [masterking32/MasterHamsterKombatBot#403]
The script version is current 

https://imgur.com/a/kgPf6JC

**Comment by Fy0urM** [comment]
no need to upload the screenshot to third party resources, you can just paste it into the input field here using ctrl+v and wait for it to load

**Comment by Fy0urM** [comment]
> The script version is current
> 
> https://imgur.com/a/kgPf6JC

This is due to the fact that the bot works with the balance received at the start of the card buying cycle and updates it only by subtracting the price of the purchased card, but during the card buying cycle the real balance increases due to passive income. we will try to fix this later.

**Comment by Homavi88** [comment]
> но я не могу найти в последней версии сценария строку с содержанием, как на вашем скриншоте `😪 Balance is too low to buy the best card: ...`

I updated the script last night.

**Comment by cmdgits** [comment]
Hello scrip not start by proxy .Please fix proxy no start .Thank you

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Fy0urM ***@***.***>
Đã gửi: Tuesday, September 10, 2024 10:16:30 PM
Đến: masterking32/MasterHamsterKombatBot ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [masterking32/MasterHamsterKombatBot] Script does not buy card (Issue #403)


In any case, your case is probably extremely rare. don't worry about 1 missing card. most likely it will be bought on the next cycle

**Comment by Homavi88** [comment]
> В любом случае, ваш случай, вероятно, крайне редкий. Не беспокойтесь о 1 пропавшей карте. Скорее всего, она будет куплена в следующем цикле

Thk 👍
