### ISSUE TITLE
Status code is not 200 

### ISSUE THREAD

**Issue by Homavi88** [masterking32/MasterHamsterKombatBot#407]
Hi 
I started receiving a message in the telegram bot in the morning.

**Comment by Fy0urM** [comment]
PR is already pending confirmation https://github.com/masterking32/MasterHamsterKombatBot/pull/406
you can replace your main.py with the modified file while we wait for the owner
https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/0f7fbf59f9ff096d76457cdbfd0b833e409042f7/main.py
