### ISSUE TITLE
My data get reseted 

### ISSUE THREAD

**Issue by cheasomnanglol12** [masterking32/MasterHamsterKombatBot#408]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Fy0urM** [comment]
what u mean?

**Comment by Fy0urM** [comment]
I suspect it's because you put your bearer token out in the open.
Removing the config from the repository will not hide your data, it will remain in the commit history, maybe a complete removal of the fork will help.

**Comment by Fy0urM** [comment]
But it will hardly help if the attacker saved your token, if I understand correctly developers do not cancel old tokens even if you get a new one.

**Comment by cheasomnanglol12** [comment]
I host it in railway for 10 days ago
