### ISSUE TITLE
Now the problem is to get Bearer Token together with Violent

### ISSUE THREAD

**Issue by vashamamasha2014** [masterking32/MasterHamsterKombatBot#410]
![image](https://github.com/user-attachments/assets/57262eda-57b7-4a04-ae19-440a15bb765d)

**Comment by Ashwin3454** [comment]
> ![image](https://private-user-images.githubusercontent.com/169598812/366755340-57262eda-57b7-4a04-ae19-440a15bb765d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjY3MTEsIm5iZiI6MTcyNjEyNjQxMSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NzU1MzQwLTU3MjYyZWRhLTU3YjctNGEwNC1hZTE5LTQ0MGExNWJiNzY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwNzMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTIzNzBiM2Y5YzMzNmJhYWIyYjJkMWFiZjYwYjU1OTFkMWI1YjcyMmRhNTFiMmFiMjNmYTU3ZjhiNzQyMjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JuTaBHyG2h8A6svkba9fCSPuekfogy-5OxWJCUKOgY)

Download & install resource override extention
https://chromewebstore.google.com/detail/resource-override/pkoacgokdfckfpndoffpifphamojphii

`Tab URL` https://web.telegram.org/a/#7018368922
`From` https://hamsterkombatgame.io/js/telegram-web-app.js?v=7.6
`To` https://evgeniyvorobev.github.io/hamster-kombat-bot/telegram-web-app.js
Reload page.

![Screenshot 2024-09-12 130549](https://github.com/user-attachments/assets/a6d77104-243f-44e5-8e56-43cd82d5b0f7)

**Comment by Fy0urM** [comment]
or simply change the tgWebAppPlatform= parameter to android for the iframe element in your browser's dev tool

**Comment by vashamamasha2014** [comment]
> или просто измените параметр tgWebAppPlatform= на android для элемента iframe в инструменте разработки вашего браузера

Thanks
