### ISSUE TITLE
UserAgent and forced platform question

### ISSUE THREAD

**Issue by ephao** [masterking32/MasterHamsterKombatBot#419]
I have several Android device UserAgent, but I see the code here forces platform identification as iOS.
`$telegram_web_app = str_replace("return webAppPlatform;", 'return "ios";', $telegram_web_app);`
The code is in hamsterkombat.io-telegram-web-app.php.

**Comment by AmirhN1382** [comment]
That code has nothing to do with bot itself, it's just simply used to make HamsterKombat accessible on Desktop.
