### ISSUE TITLE
This feature is really needed

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#420]
Automatic solving of mini-games is really needed
If you can add both mini games it will be really awesome (key and coin)
**but key mini game is important**

**Comment by Fy0urM** [comment]
if you need this functionality you can uncomment lines 1911-1914
https://github.com/masterking32/MasterHamsterKombatBot/blob/8a492871505bcea21a9a70a7e302dc94d6f40a62/main.py#L1911
just be aware that you do so at your own risk.

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/268
