### ISSUE TITLE
Proxy Reconnect Issue

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#421]
I woke up at 9am and checked the bot and found it stuck with the error `[MasterHamsterKombatBot] [2024-09-10 04:05:09] [ERROR] [Account 10]: ✖ Error: HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/1/login-client (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')))`

I know its because of my proxy but the proxy came back up not long later and the bot doesn’t try to connect again so just stays stuck until I manually restart it.

Im using [Webshare](https://www.webshare.io) as recommended so im using "good proxies".  I checked again and again I found 2 bots closed on their own.

**Comment by Fy0urM** [comment]
> (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response')

**Comment by masterking32** [comment]
Unrelated to the project: use paid proxies. If you encounter any issues with proxies, please contact your proxy support. Also, stop creating duplicate issues.

**Comment by tboy1337** [comment]
@masterking32 it clearly is related to the project, I do use paid proxies from the service you recommend and if you didnt close my original issue straight away without waiting for a reply/update/clarification from me what do you expect?
