### ISSUE TITLE
Response: Internal server error

### ISSUE THREAD

**Issue by vstri** [masterking32/MasterHamsterKombatBot#423]
[MasterHamsterKombatBot] [2024-09-13 17:13:42] [INFO] [Account S]: 🛸 Getting basic account data.
[MasterHamsterKombatBot] [2024-09-13 17:13:45] [ERROR] [Account S]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-13 17:13:45] [ERROR] [Account S]: ✖ Response: Internal server error

**Comment by qawechi** [comment]
the same.

**Comment by qawechi** [comment]
No worries after some minz we all get banned. Lol

**Comment by ItsAmirAT** [comment]
no answer?

**Comment by Fy0urM** [comment]
unknown errors based on bearer token as I understand because requests to api with certain tokens cause an error, without token api says wrong token, performance is gradually restored, but what is the exact cause is unclear.

**Comment by qawechi** [comment]
Mine is fixed. No problems. The bot is running.
