### ISSUE TITLE
Get Config error 500

### ISSUE THREAD

**Issue by johnnykor82** [masterking32/MasterHamsterKombatBot#430]
Bot screen 
<img width="743" alt="Снимок экрана 2024-09-14 в 08 20 30" src="https://github.com/user-attachments/assets/e54bf829-18a5-4e28-8ced-b9bcd67730e2">

WebApp screen 
<img width="445" alt="Снимок экрана 2024-09-14 в 08 17 31" src="https://github.com/user-attachments/assets/4278297b-8125-4593-877d-71bb8d15dff6">

Console screen
<img width="798" alt="Снимок экрана 2024-09-14 в 08 21 49" src="https://github.com/user-attachments/assets/09efa039-4da0-45c3-afab-125e92073181">

In telegram Hamster not working too.

**Comment by sweetlilmre** [comment]
Started happening at around 05h00 GMT. Either the server is down or everyone is banned 🤣

**Comment by sweetlilmre** [comment]
Back online.
