### ISSUE TITLE
Why is this？HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/register-event (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

### ISSUE THREAD

**Issue by Zhangxiaokang123** [masterking32/MasterHamsterKombatBot#431]
HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/register-event (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
![image](https://github.com/user-attachments/assets/23fbc05f-a27b-4f52-b544-74ef522819e8)

**Comment by Ruslanik77** [comment]
> HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/register-event (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> ![image](https://github.com/user-attachments/assets/23fbc05f-a27b-4f52-b544-74ef522819e8)
> 

Hide Ball

POST /promo/1/login-client HTTP/1.1
Host: api.gamepromo.io
User-Agent: UnityPlayer/2022.3.38f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)
Accept-Encoding: deflate, gzip
accept: application/json
Content-Type: application/json
X-Unity-Version: 2022.3.38f1
Content-Length: 146

{"appToken":"4bf4966c-4d22-439b-8ff2-dc5ebca1a600","clientId":"ef3da8de6c0850a9deb6e2e521ccf0a1","clientOrigin":"android","clientVersion":"1.2.4"}

POST /promo/1/register-event HTTP/1.1
Host: api.gamepromo.io
User-Agent: UnityPlayer/2022.3.38f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)
Accept-Encoding: deflate, gzip
accept: application/json
Content-Type: application/json
Authorization: Bearer 4bf4966c-4d22-439b-8ff2-dc5ebca1a600:android:ef3da8de6c0850a9deb6e2e521ccf0a1:8Cl9vs2KzYc:1726303336257
X-Unity-Version: 2022.3.38f1
Content-Length: 149

{"promoId":"4bf4966c-4d22-439b-8ff2-dc5ebca1a600","eventId":"a0168643-b3a5-44b7-8bff-2528b48a7f4a","eventOrigin":"undefined","eventType":"undefined"}

POST /promo/1/create-code HTTP/1.1
Host: api.gamepromo.io
User-Agent: UnityPlayer/2022.3.38f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)
Accept-Encoding: deflate, gzip
accept: application/json
Content-Type: application/json
Authorization: Bearer 4bf4966c-4d22-439b-8ff2-dc5ebca1a600:android:ef3da8de6c0850a9deb6e2e521ccf0a1:8Cl9vs2KzYc:1726303660835
X-Unity-Version: 2022.3.38f1
Content-Length: 50

{"promoId":"4bf4966c-4d22-439b-8ff2-dc5ebca1a600"}

**Comment by Zhangxiaokang123** [comment]
> > HTTPSConnectionPool(host='api.gamepromo.io', port=443): Max retries exceeded with url: /promo/register-event (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> > ![image](https://private-user-images.githubusercontent.com/86096237/367495434-23fbc05f-a27b-4f52-b544-74ef522819e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjI5NDEsIm5iZiI6MTcyNjMyMjY0MSwicGF0aCI6Ii84NjA5NjIzNy8zNjc0OTU0MzQtMjNmYmMwNWYtYTI3Yi00ZjUyLWI1NDQtNzRlZjUyMjgxOWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE0MDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmJiYzE2YWUwNzBiYmNmNzFmOTgzYTFkMjFmMWIwYjU4YzVhYTUzOGI5ZDE4MTE4MzA4NWM4ZTg4NTM2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrE4XoPhHsnjEdbG4vuTfrtRn9Mojf2ewsTrQ-2gRpA)
> 
> Hide Ball
> 
> POST /promo/1/login-client HTTP/1.1 Host: api.gamepromo.io User-Agent: UnityPlayer/2022.3.38f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV) Accept-Encoding: deflate, gzip accept: application/json Content-Type: application/json X-Unity-Version: 2022.3.38f1 Content-Length: 146
> 
> {"appToken":"4bf4966c-4d22-439b-8ff2-dc5ebca1a600","clientId":"ef3da8de6c0850a9deb6e2e521ccf0a1","clientOrigin":"android","clientVersion":"1.2.4"}
> 
> POST /promo/1/register-event HTTP/1.1 Host: api.gamepromo.io User-Agent: UnityPlayer/2022.3.38f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV) Accept-Encoding: deflate, gzip accept: application/json Content-Type: application/json Authorization: Bearer 4bf4966c-4d22-439b-8ff2-dc5ebca1a600:android:ef3da8de6c0850a9deb6e2e521ccf0a1:8Cl9vs2KzYc:1726303336257 X-Unity-Version: 2022.3.38f1 Content-Length: 149
> 
> {"promoId":"4bf4966c-4d22-439b-8ff2-dc5ebca1a600","eventId":"a0168643-b3a5-44b7-8bff-2528b48a7f4a","eventOrigin":"undefined","eventType":"undefined"}
> 
> POST /promo/1/create-code HTTP/1.1 Host: api.gamepromo.io User-Agent: UnityPlayer/2022.3.38f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV) Accept-Encoding: deflate, gzip accept: application/json Content-Type: application/json Authorization: Bearer 4bf4966c-4d22-439b-8ff2-dc5ebca1a600:android:ef3da8de6c0850a9deb6e2e521ccf0a1:8Cl9vs2KzYc:1726303660835 X-Unity-Version: 2022.3.38f1 Content-Length: 50
> 
> {"promoId":"4bf4966c-4d22-439b-8ff2-dc5ebca1a600"}

bro,whats meaning？
