### ISSUE TITLE
Is this due to an official server issue?：Event registration for Tile Trio was successful, but no code was provided, retry in 35 seconds.

### ISSUE THREAD

**Issue by Zhangxiaokang123** [masterking32/MasterHamsterKombatBot#439]
Is this due to an official server issue?
![image](https://github.com/user-attachments/assets/1a935a82-c203-4e8b-a4bd-f05586a7ee6c)

**Comment by Fy0urM** [comment]
> Is this due to an official server issue?
> ![image](https://github.com/user-attachments/assets/1a935a82-c203-4e8b-a4bd-f05586a7ee6c)
> 

This is not a problem, it's just a display of bot activity during the key retrieval process. To retrieve a key, the client (the actual game or in this case the bot) must send a certain number of register-event requests in order to be given the key.

**Comment by Zhangxiaokang123** [comment]
> > 这是由于官方服务器问题吗？
> > ![图像](https://private-user-images.githubusercontent.com/86096237/367553384-1a935a82-c203-4e8b-a4bd-f05586a7ee6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNjUzMTcsIm5iZiI6MTcyNjM2NTAxNywicGF0aCI6Ii84NjA5NjIzNy8zNjc1NTMzODQtMWE5MzVhODItYzIwMy00ZThiLWE0YmQtZjA1NTg2YTdlZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDAxNTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZWIzNWM2Y2EzNzdkMGEzYTU1YjYzZWMyYjYwMDA0MDgwMmU5NzI2NzgxMzcyNDg2YjgwZTk1ODBhMGI1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s5cW5gikhL6ZKNgxNKCjRXzzzb4b0YoLUrfpaqxAbTw)
> 
> 这不是问题，这只是密钥检索过程中机器人活动的展示。要检索密钥，客户端（实际游戏或本例中的机器人）必须发送一定数量的注册事件请求才能获得密钥。

Thanks！bro

**Comment by Zhangxiaokang123** [comment]
> > Is this due to an official server issue?
> > ![image](https://private-user-images.githubusercontent.com/86096237/367553384-1a935a82-c203-4e8b-a4bd-f05586a7ee6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNjU0MzksIm5iZiI6MTcyNjM2NTEzOSwicGF0aCI6Ii84NjA5NjIzNy8zNjc1NTMzODQtMWE5MzVhODItYzIwMy00ZThiLWE0YmQtZjA1NTg2YTdlZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDAxNTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODQyYmMxMWQ0MTBiNmU4OTdmMzQwOGQ3YTAyODg3MDdhZWVmYTQ0NjMyY2ZhYTgzNzI3NmI0Yzk5ODdmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EOnDHFvblHmahgPu_11_zCeRNVUUfNoLLicGXB_5zxo)
> 
> This is not a problem, it's just a display of bot activity during the key retrieval process. To retrieve a key, the client (the actual game or in this case the bot) must send a certain number of register-event requests in order to be given the key.

bro，Do you know this？ 
![image](https://github.com/user-attachments/assets/4abe0fd5-f2cb-405f-8715-b8a3e189b5a2)

**Comment by Fy0urM** [comment]
SSL connection error between you machine and server

**Comment by Zhangxiaokang123** [comment]
I hava too many error
1.
![image](https://github.com/user-attachments/assets/59f33682-d20c-442d-8de8-f5a51ce52e11)
2.
![image](https://github.com/user-attachments/assets/cf5b5f67-1c3a-4bf5-b665-a4fd07405b86)

**Comment by Zhangxiaokang123** [comment]
> SSL connection error between you machine and server

How can I solve this problem？bro

**Comment by Fy0urM** [comment]
If you are using a proxy, maybe the proxy is the problem, I can't say for sure.
