### ISSUE TITLE
Request for update 

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#44]
Hello, will there be an update to the bot that will be able to solve the puzzle and receive keys automatically?
Thank you

**Comment by Neo19867** [comment]
it will be awesome))

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/45

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/45
