### ISSUE TITLE
Daily Combo Is Disabled?

### ISSUE THREAD

**Issue by HaadxEason** [masterking32/MasterHamsterKombatBot#448]
![image](https://github.com/user-attachments/assets/66ac5d61-aa36-4319-9471-f99878eb31a1)

![image](https://github.com/user-attachments/assets/f14cced8-3930-4f59-8639-814f95f4188a)

My daily combo is enable in config but as you can see it says this why?

**Comment by Fy0urM** [comment]
![image](https://github.com/user-attachments/assets/cc2920f1-4ed0-4fce-b1c7-e35e3bd030e6)
nope

**Comment by HaadxEason** [comment]
> ![image](https://private-user-images.githubusercontent.com/39411717/367582721-cc2920f1-4ed0-4fce-b1c7-e35e3bd030e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDUwODYsIm5iZiI6MTcyNjQwNDc4NiwicGF0aCI6Ii8zOTQxMTcxNy8zNjc1ODI3MjEtY2MyOTIwZjEtNGVkMC00ZmNlLWIxYzctZTM1ZTNiZDAzMGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YzEzNjE0YjhkNGZlZTZlYzZkZmM1MWM0ZDg3NDA3MmFkNjdkY2ViODQwYmUxYTIzMWQyMmFmNmE2NDRjOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gjcT6yV0WLNylmjDiiMu_oG6ZoW1_RoV7m585dlIU90) nope

How to fix it please tell?

**Comment by Fy0urM** [comment]
idk, wait, i check original bot

**Comment by Fy0urM** [comment]
hhhmmm, u are right. something wrong
![image](https://github.com/user-attachments/assets/0cb724f1-306c-4bec-a7d6-cddb51e20ac1)

**Comment by Fy0urM** [comment]
i found,
replace "auto_claim_daily_combo" in config to "auto_daily_combo_enable"

**Comment by Fy0urM** [comment]
PR in the way
