### ISSUE TITLE
The code will get stuck in this step and will not report an error.

### ISSUE THREAD

**Issue by 284267** [masterking32/MasterHamsterKombatBot#451]
The code is stuck in this place, and there is no reason for the error. Can it be solved?
![Screenshot_2024-09-16-07-17-58-112_org connectbot](https://github.com/user-attachments/assets/f94452aa-cd8c-425a-8f02-9c60bc362bd9)

**Comment by Fy0urM** [comment]
Try to focus console and press enter, may some your inputs pause output

**Comment by 284267** [comment]
Ok, I'll try. Thank you, sir.

**Comment by tboy1337** [comment]
It will do that for me sometimes before it errors and moves on to the next account, I think they are proxy/hamster server issues.
