### ISSUE TITLE
Character issue

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#452]
Some of the characters are not showing correctly, also `Not enough coins to buy a daily combo.` message doesn't have an icon.

![error](https://github.com/user-attachments/assets/89bcc074-9575-4072-b7d7-194a1df332e0)

**Comment by Fy0urM** [comment]
because there's no emoji in this line.

![image](https://github.com/user-attachments/assets/d34b2da5-155e-4cb5-9918-d22330cec178)

**Comment by tboy1337** [comment]
Just seems like it should for continuity but the main issue is the other missing icons/characters.

**Comment by Fy0urM** [comment]
i'm not sure what you mean.

**Comment by tboy1337** [comment]
4th line down from the top, look at the character to the left of `Getting basic account data.`

**Comment by Fy0urM** [comment]
most likely this is because the system in which the script is running does not support emoji. it's termux or what?

**Comment by tboy1337** [comment]
Windows 10 running python 3.12.6, I run main.py through CMD through python.exe (`python main.py`).

**Comment by Fy0urM** [comment]
indeed, maybe it's the standard windows terminal that doesn't support emoji.
![image](https://github.com/user-attachments/assets/1e71f414-e147-4f76-9aca-42a6c1ae0bab)

**Comment by Fy0urM** [comment]
I'm using this terminal by default, it supports emoji.

https://www.microsoft.com/store/productId/9N0DX20HK701

**Comment by Fy0urM** [comment]
sources
https://github.com/microsoft/terminal

**Comment by tboy1337** [comment]
Yea i guess i should probably start using it lol

**Comment by tboy1337** [comment]
just tried it, it fixes the emoji issue but creates another one so i can live with it lol.

**Comment by Fy0urM** [comment]
what's the new problem?

**Comment by tboy1337** [comment]
I’m running the updater i made alongside the bot, i have 16 bots plus 16 updaters, i run the updater with py.exe and the bot with python.exe so there are two different taskbar window groups which i can tile and see what is actually going on but when i open them all with terminal they have the same taskbar window grouping so I cant tile it without the windows being too small.

**Comment by Fy0urM** [comment]
I don't quite understand why you need a separate Updater for each bot, try to learn what symlink is.
I sketched a small bat script that creates a specified number of clones and creates symbolic links to the necessary files for each clone, all you need to do is put the config file separately in each clone folder and run the bot from the clone folder. in this case you will only need 1 updater process for the main folder where the fork itself is located. and if necessary you will need to terminate all running bot processes and restart them.

the advantage is that symlink will always point to the file as long as it exists, even if you delete the original file and create another file named after the original, symlink will link to it.

<details>
<summary>symlinker.bat</summary>

```batch
@echo off
@chcp 65001 >nul
setlocal enabledelayedexpansion

:: variables
set "sourceFolder=%userprofile%\Desktop\TgCryptoBots\HamsterKombatBot\fork"
set "clonesFolder=%userprofile%\Desktop\TgCryptoBots\HamsterKombatBot\clones"
set "botsCount=3"

:: files to symlink
set files[1]=main.py
set files[2]=promogames.py
set files[3]=utilities.py
set files[4]=warna.py
set files[5]=banner.py

:: index of last file
set num_files=5

:: check if folder for clones already exists
if exist %clonesFolder% (
    echo Folder for clones already exists. >nul
) else (
    mkdir %clonesFolder%
)

:: main loop
for /L %%i in (1,1,%botsCount%) do (
    :: set selected clone path in loop
    set "new_folder=!clonesFolder!\bot%%i"

    :: check if folder already exists
    if exist "!new_folder!" (
        echo Folder !new_folder! already exists. >nul
    ) else (
        mkdir "!new_folder!" >nul
        echo Folder created: !new_folder! >nul
    )

    :: creating symlinks in clone folder loop
    for /L %%j in (1,1,%num_files%) do (
        echo [%%j] - !files[%%j]!
        set "file=!files[%%j]!"
        set "link=!new_folder!\!file!"

        :: check if symlink already exists
        if exist "!link!" (
            echo Link to !file! already exists in !new_folder!. >nul
        ) else (
            mklink "!link!" "%source_folder%\!file!"
            echo Symlink to file !file! created in !new_folder!. >nul
        )
    )
)
```

**Comment by tboy1337** [comment]
@Fy0urM what do you mean by fork in the code?  Also will my updater work with this set up?  Will it create differently named clone folders?

**Comment by Fy0urM** [comment]
fork means your copy of someone else's repository, I forgot that you work with your own repository. but it doesn't matter, it is enough to have one folder with the main repository as a base and updates, and to run bots from the created “clones”. symlinker creates clone folders in the format `bot#` where `#` is the number of the clone.
In bat you set the required number of clones,
`set “botsCount=3”`.
the loop runs from 1 to botsCount and creates a clone folder for each iteration.
but most likely you will have to modify your updater to close all clone processes when you need to update and run each clone looking in the clones folder.

**Comment by Fy0urM** [comment]
this is just my suggestion, nothing more. i don't insist on using it. it just seemed to me that having 1 updated repository is easier than constantly checking for updates for each bot.

**Comment by tboy1337** [comment]
Ah i see, ok thanks for the code, i was just wondering why fork, maybe master would be a better name for it.  Currently the updater looks for the process running from the same folder as itself, it took a while to get it working so idk if i want to start again to get it working lol.
