### ISSUE TITLE
I lost my telegram account, need to select withdrawal method 

### ISSUE THREAD

**Issue by Gantar15** [masterking32/MasterHamsterKombatBot#454]
Hi I lost my tg account but I still have access to the bot. I was wondering if you could help me out. I linked my wallet, but now I need to choose a withdrawal method and I don't have access to the account :( . If someone would add a code that can select the withdrawal method it would be great.

**Comment by kglaynyi** [comment]
I think the withdrawl method will be default you linked earlier because when I linked to exchange,I have to reset early linked ton wallet. Good Luck.

**Comment by masterking32** [comment]
Duplicate: https://github.com/masterking32/MasterHamsterKombatBot/discussions/446
