### ISSUE TITLE
Auto keys

### ISSUE THREAD

**Issue by RKx25** [masterking32/MasterHamsterKombatBot#46]
Can you please add auto key completion to the script?
![image](https://github.com/user-attachments/assets/083663cd-a1b5-4117-a1e6-e751c72be2e3)

**Comment by XShaan** [comment]
soon

> Can you please add auto key completion to the script? ![image](https://private-user-images.githubusercontent.com/68664772/350721840-083663cd-a1b5-4117-a1e6-e751c72be2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTEyMTIsIm5iZiI6MTcyMTUxMDkxMiwicGF0aCI6Ii82ODY2NDc3Mi8zNTA3MjE4NDAtMDgzNjYzY2QtYTFiNS00MTE3LWExZTYtZTc1MWM3MmJlMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDIxMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZTU1ZTA0ZWRmOGIwNDNjMzkwMTM0MjAxOTMwZjE5MWU2OWQ4NzE5NTJlYWEzZWNlZTAyNzE2MWYzNDFkZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U7tfiP1Z0-tNsnSYWC52xJQNBluSEw7u6sShp9dkIpI)

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/45
