### ISSUE TITLE
Hamster Kombat if detecting games installed or not. if not, they will flag your account, and cut you off the airdrop?

### ISSUE THREAD

**Issue by ZProtons** [masterking32/MasterHamsterKombatBot#460]
**Is your feature request related to a problem? Please describe.**
There are rumors spreading that Hamster kombat is checking for apps installed, if yes, then you are safe. if not, your account will be flagged.

**Describe the solution you'd like**
A way to send fake response to requests (where hamster checks for installed apps).

**Describe alternatives you've considered**
Using actual keygens, from telegram, and installing the apps in my actual phone.

**Additional context**

**Comment by Fy0urM** [comment]
how can a website that opens in the built-in Telegram browser find out what apps are installed on your phone?

**Comment by autoattack999** [comment]
> **Is your feature request related to a problem? Please describe.** There are rumors spreading that Hamster kombat is checking for apps installed, if yes, then you are safe. if not, your account will be flagged.
> 
> **Describe the solution you'd like** A way to send fake response to requests (where hamster checks for installed apps).
> 
> **Describe alternatives you've considered** Using actual keygens, from telegram, and installing the apps in my actual phone.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Just RUMOR~

**Comment by ZProtons** [comment]
> how can a website that opens in the built-in Telegram browser find out what apps are installed on your phone?

Yeah me too. but all these influencers are making me nervous

**Comment by ZProtons** [comment]
Having a app check for a app installed in latest android version is hard enough, let alone a  app-in-app, and that too a web-app. But I am extremely nervous

**Comment by Fy0urM** [comment]
what influencers? what are you talking about?

**Comment by ZProtons** [comment]
https://www.binance.com/en/square/post/13648241410114
this is one of many

**Comment by Fy0urM** [comment]
sounds like bullshit.

**Comment by ZProtons** [comment]
yeah, but it is making me extremely nervous. am I safe?

**Comment by Fy0urM** [comment]
Even if it somehow magically turns out to be true. Is it too late to fix anything? The keys have already been obtained, and the only way to get rid of them is to reset the account

**Comment by Fy0urM** [comment]
safe ot not, you can ask the developers of hamster kombat.

**Comment by ZProtons** [comment]
I dunno, I generated 1012 keys. and Ima stop now.

**Comment by ZProtons** [comment]
see, this is what I meant
![image](https://github.com/user-attachments/assets/c35e7de7-2def-4fde-92f1-f9d844636064)

**Comment by Fy0urM** [comment]
my account feels fine, no achievement received.

**Comment by ZProtons** [comment]
And it gets worse,
![image](https://github.com/user-attachments/assets/fb706604-9ade-40b8-9d52-ee36af47ec61)
