### ISSUE TITLE
Too expensive to buy in parallel

### ISSUE THREAD

**Issue by nightlifeav1** [masterking32/MasterHamsterKombatBot#462]
<img width="558" alt="{70060578-5FE4-46E7-BF2B-B9D837987AAB}" src="https://github.com/user-attachments/assets/204243cf-5185-4436-9c1b-d7f896f71937">
Getting this warning  repeatedly and now new purchase is being done, How do i fix it.

**Comment by Fy0urM** [comment]
> <img alt="{70060578-5FE4-46E7-BF2B-B9D837987AAB}" width="558" src="https://private-user-images.githubusercontent.com/177486358/368246280-204243cf-5185-4436-9c1b-d7f896f71937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTAyNzcsIm5iZiI6MTcyNjU4OTk3NywicGF0aCI6Ii8xNzc0ODYzNTgvMzY4MjQ2MjgwLTIwNDI0M2NmLTUxODUtNDQzNi05YzFiLWQ3Zjg5NmY3MTkzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNjE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzY3Y2MwMDQzZTI1ZjM1YTg2YWE3ZjY5ZWMwNzZkZjJmOTM4NTBhYTNhMDE4ZDJkMWQyNTViZjEyNzE1YmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hZMtqKz0Gshi_E-h7JyvYTG2q2STrBKuagAFi28QSlo"> 
read carefully

**Comment by nightlifeav1** [comment]
I have read . Just didn't understand where and what value should i type.

**Comment by Fy0urM** [comment]
where are the settings for the bot stored?

**Comment by nightlifeav1** [comment]
Never mind . just started using another bot
