### ISSUE TITLE
Is it profitable to upgrade cards with a high value at the end of Season 1?

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterHamsterKombatBot#464]
refers to config.py.example update `e8af4d6`

❌ "parallel_upgrades_max_price_per_hour": 1000❌
✅ "parallel_upgrades_max_price_per_hour": 6000✅

i think 1000 was good.

**Comment by tboy1337** [comment]
I change it to 10000, seems like a better strategy imo

**Comment by Ashwin3454** [comment]
> I change it to 10000, seems like a better strategy imo

So, it will decrease the passive income currency, but that won't affect the airdrop allocation points, right?
1000, 6000, 10000. which is best?

**Comment by XenMe** [comment]
if you check the airdrop tab, passive income matters, so you should spend every penny to upgrade the card and increase your passive income other than save coins

**Comment by Ashwin3454** [comment]
> if you check the airdrop tab, passive income matters, so you should spend every penny to upgrade the card and increase your passive income other than save coins

My PPH is 9.7M, and I have 3.5B coins. Should I upgrade my cards, or is it better to save my coins since the season is ending soon?
