### ISSUE TITLE
Add buy specific card and skins

### ISSUE THREAD

**Issue by Hzone-glitch** [masterking32/MasterHamsterKombatBot#471]
Please add new ability to upgrade specific card and auto buy skins

**Comment by qawechi** [comment]
why do u need to upgrade specific cards? the bot normally is doing that based on you interest. why do u  wanna do something that is less beneficial to you?

**Comment by Hzone-glitch** [comment]
For unlock archivment level 25 card

**Comment by Pawansingh333** [comment]
how to stop buying card?
