### ISSUE TITLE
Getting this error everytime from today morning

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterHamsterKombatBot#473]
But working on telegram

![Screenshot 2024-09-19 105341](https://github.com/user-attachments/assets/9477d9c6-1346-4e29-98a9-af215d93cd38)

**Comment by Fy0urM** [comment]
This error is not related to the main app, but to the api playground games server, so it has nothing to do with the telegram app

**Comment by Ashwin3454** [comment]
> This error is not related to the main app, but to the api playground games server, so it has nothing to do with the telegram app

can i stop running the app or disable playground games?

**Comment by Fy0urM** [comment]
idk, i'm relatively stable, I get 1 error per cycle per account.

**Comment by Fy0urM** [comment]
nothing has changed as far as I know, my bots are fine.
