### ISSUE TITLE
New Playground game

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#475]
There is a new playground game [Infected Frontier](https://play.google.com/store/apps/details?id=com.microminimice.infectedfrontier)

Node.js code:
```js
  INFCT: async ({ collect, delay, event, id, instance, login, origin, setup }) => {
    setup('app-token', 'eb518c4b-e448-4065-9d33-06f3039f0fcb');
    setup('promo-id', 'eb518c4b-e448-4065-9d33-06f3039f0fcb');
    setup('unity-version', '2022.3.21f1');

    if (origin === 'ios') {
      setup('user-agent', 'InfectedFrontier/11 CFNetwork/1568.100.1 Darwin/24.0.0');
    } else {
      setup('user-agent', 'UnityPlayer/2022.3.21f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)');
    }

    await login({ clientId: id('uuid'), clientOrigin: origin });

    if (TIMING_STRATEGY === 'realistic') {
      await delay(70_000);
    }

    while (!instance.hasCode) {
      await delay(TIMING_STRATEGY === 'realistic' ? 80_000 : 20_000);
      await event({ eventId: id('uuid'), eventOrigin: 'undefined', eventType: 'biker' });
    }

    await collect();
  },
```

[hamster-kombat-playground-games-promo-keys-generator.js](https://gist.github.com/delasy/96c5340fc5e0617ddc1ff4ddb458d968#file-hamster-kombat-playground-games-promo-keys-generator-js)

**Comment by tboy1337** [comment]
Node.js code:
```js
  INFCT: async ({ collect, delay, event, id, instance, login, origin, setup }) => {
    setup('app-token', 'eb518c4b-e448-4065-9d33-06f3039f0fcb');
    setup('promo-id', 'eb518c4b-e448-4065-9d33-06f3039f0fcb');
    setup('unity-version', '2022.3.21f1');

    if (origin === 'ios') {
      setup('user-agent', 'InfectedFrontier/11 CFNetwork/1568.100.1 Darwin/24.0.0');
    } else {
      setup('user-agent', 'UnityPlayer/2022.3.21f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)');
    }

    await login({ clientId: id('uuid'), clientOrigin: origin });

    if (TIMING_STRATEGY === 'realistic') {
      await delay(70_000);
    }

    while (!instance.hasCode) {
      await delay(TIMING_STRATEGY === 'realistic' ? 80_000 : 20_000);
      await event({ eventId: id('uuid'), eventOrigin: 'undefined', eventType: 'biker' });
    }

    await collect();
  },
```

**Comment by Zhangxiaokang123** [comment]
> There is a new playground game [Infected Frontier](https://play.google.com/store/apps/details?id=com.microminimice.infectedfrontier)
> 
> Node.js code:
> 
> ```js
>   INFCT: async ({ collect, delay, event, id, instance, login, origin, setup }) => {
>     setup('app-token', 'eb518c4b-e448-4065-9d33-06f3039f0fcb');
>     setup('promo-id', 'eb518c4b-e448-4065-9d33-06f3039f0fcb');
>     setup('unity-version', '2022.3.21f1');
> 
>     if (origin === 'ios') {
>       setup('user-agent', 'InfectedFrontier/11 CFNetwork/1568.100.1 Darwin/24.0.0');
>     } else {
>       setup('user-agent', 'UnityPlayer/2022.3.21f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)');
>     }
> 
>     await login({ clientId: id('uuid'), clientOrigin: origin });
> 
>     if (TIMING_STRATEGY === 'realistic') {
>       await delay(70_000);
>     }
> 
>     while (!instance.hasCode) {
>       await delay(TIMING_STRATEGY === 'realistic' ? 80_000 : 20_000);
>       await event({ eventId: id('uuid'), eventOrigin: 'undefined', eventType: 'biker' });
>     }
> 
>     await collect();
>   },
> ```
> 
> [hamster-kombat-playground-games-promo-keys-generator.js](https://gist.github.com/delasy/96c5340fc5e0617ddc1ff4ddb458d968#file-hamster-kombat-playground-games-promo-keys-generator-js)

hamster adds  a new game Among Water again

**Comment by httpsTeabagexe** [comment]
New game factory world https://play.google.com/store/search?q=factory%20world&c=apps

**Comment by tboy1337** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/pull/476

**Comment by tboy1337** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/pull/477

**Comment by AmirhN1382** [comment]
added
