### ISSUE TITLE
Hamster Kombat Snapshot

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#481]
The snapshot will happen on September 20, 18:00 UTC 

[https://bitpinas.com/business/hamster-kombat-snapshot-date-set/](https://bitpinas.com/business/hamster-kombat-snapshot-date-set/)

**Comment by Microzibert** [comment]
Do I understand correctly that coin mining will be finished on September 20?

**Comment by tboy1337** [comment]
no, season 1 will officially end of September 20, they teased a Season 2 airdrop also.

**Comment by AmirhN1382** [comment]
Just in time to finish https://github.com/masterking32/MasterCryptoFarmBot ASAP and focus on multiple bots i guess.

**Comment by tboy1337** [comment]
I hope you guys get the framework and some modules done quickly xD

**Comment by stefan2101-fast** [comment]
> No, Season 1 will officially end on September 20 and at 18:00 they will decide everyones Season 1 airdrop, they teased a Season 2 airdrop also.

18:00  which is region? russion?

**Comment by ZProtons** [comment]
18:00 UTC, convert it to your time zone

**Comment by tboy1337** [comment]
1 hour to go
