### ISSUE TITLE
Hamster Profile Avatar

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterHamsterKombatBot#482]
When i clicked on top players profile picture i found a link.
i hope it will help developers to identify how they change profile picture.

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5167ebec-3ca4-42f7-a58a-a300fbb0d54b">

**Comment by tboy1337** [comment]
[https://www.youtube.com/watch?v=p4aPSN_mVZI](https://www.youtube.com/watch?v=p4aPSN_mVZI)

**Comment by Ashwin3454** [comment]
> https://www.youtube.com/watch?v=p4aPSN_mVZI

It's not working dear

**Comment by tboy1337** [comment]
It probably takes some time to update.
