### ISSUE TITLE
A new Update?

### ISSUE THREAD

**Issue by ZProtons** [masterking32/MasterHamsterKombatBot#485]
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [INFO] [Account 1]: 🌌 Starting account.
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [INFO] [Account 1]: 📡 Getting account IP.
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [ERROR] [Account 1]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [ERROR] [Account 1]: ✖ Response: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "api.hamsterkombatgame.io",cType: 'managed',cNounce: '91366',cRay: '8c61b963980641a4',cHash: '690a68096be1067',cUPMDTk: "\/ip?__cf_chl_tk=N2vkVNM7X6lfXw.qfn8knPIHbVKzDZc7kqcZ5xwNG1Q-1726834350-0.0.1.1-2600",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '390000',cTplV: 5,cTplB: 'cf',cK: "",fa: "\/ip?__cf_chl_f_tk=N2vkVNM7X6lfXw.qfn8knPIHbVKzDZc7kqcZ5xwNG1Q-1726834350-0.0.1.1-2600",md: "wdeiqRt.a4GR0yNmGzhGQs7p5jlP.oC.oO0SCPDLI8o-1726834350-1.1.1.1-VCJTgCa8pWzt6JNuwcy7zSfm7rXB1XhYi.5SpTu1xKrVFG.xU..4TAqB7lzyi35Mbq39oFb5LAevln30E66k0RgfmXoctHbgn7.9n.UMV0maphfiYMnu78c5U6l7KNLmBXTs_1kRrUrq3u_WlH3FehAVDm_BHGV.76C.Hd1QOgVIIcSPtOGeTD0QIZ1Eq0aaR2OJHGIxO4OgjNb7TpX7CyDR3X8VgOE.eNKokTCTGIHtaJHvNGZHmlG78ffgZZ7K6k3WFGTvZp0rIfxmGHYeFZhAstalXeSRzsfGaTMH1IscErJP2ovwHstZWHJ6DqGpM_rVir8bXFmlhvVb6jSTnU6DBcGLoIfqtpuByv1VP32uWxaQ8phz8YFJdqtn5z_okofHgSAIw5eFazBsQUqIq1DyxJZqEp7ItV8FBAyCCmaj5Iwb9wwTLDJ67YEWkzYTJNQq3TQIWqBX7f24_7QwoWlKF8FPxhAirNUUVYPSd9xR3yMhrxPZJVBj5BMzju5CMahRoCp.d0zCS8i.rlYKAGBE1CZtKkGJzKrrQz_FPm4hIxCpsW5b57qQXzOntZ0AoJ0YPoirR.Qx3wts6FrPK5i8VzOvfnhU32dVNerM5PsHLeOj8AX_kw91uVesx0AxNK4V144kYpjk2QiC_JFmM2ezBWnYob78NUoyj8VR2_s_.Dkd9bFJhogvYppuihk4_G4YCRK8oCLhXkKBRmE.a._n.xucABqKplqN4lPriSXduWeCGYq4Yl4EAf0RNpZyCClP5fTJLq2l_DYBiVnHqUdFZxC.JY8ZkuhoPPzYX58LEZpGvqKgXElJW94RI3QaCc.FiMo0aYOLjWLGAqZEWRAyHdhO_bfFShYnOUP28JxUoovavhikaBti47B7sICa1_.LPoS_na5kyTelPWis8ODvr_FyTqNC9QJ0vALtzRd_Lc0aaVnCUqkGeXHEM2.qAYYQ.x.9b60hxfIwTOXKW.faErtBFn5.uYQKWrURpe6uiqhWJYnGUjD2_PqqniX1.9ogC.GZAiL5Tg72LZzDW9nPHQPiJ1N_3qAC_KuOc_pbaG8rMVL.GYit_N7EWzlDmXOJnkuVLeSg1wtsxk9ovx9sUtIFPNDO3BtCDDSx0Li.iRDkXN_zPL7ogUhDMNEa2MH0FUi1W77TA9.e9R81_UXAPmEowY6xZJfUDCwqZkOV9q_wb4NBE4xQlbILN5yYt_CMbgI.OEZvVOvxu.bCRh3QodoJ.FT3cKIR4iYLITSsZk6W6Wc3EUaQxtRwCGQ1cWJKj7sMnv.hEcXKwqrIGdcEDxiLkGFbA..qUET4y2xE4aQaf_o6XEw2C0Fehmlg_9CDVBypcwW0pytRylM5D.epLT8hl9TlhNbct66Q4MDktzfZxSBfFPYAuBMIWuhbMe12viQQGDQL9cP1dN0KGWOq3ZIR2rsQbe2jgBo6zrFwloIfJSRg6km5nKE8XB8NsVHZTRWXFX8iUJCz84fsZDJIH1I9woE2JSJVtRKemJAxjxVwQNVsIjVsGMPSQBg13zYbgm0aPdPYStWrpCJhMrA6PvUPiHAjyn8SkabIU2Ax0bTwHDRn2alldzprD3GJ2sGDE2d__YVUThNbix5zn6lrZ02AECzdwLkVFPNOzRjuD1ZHqeBvGGxozTy68lDtKUuOjdY9MEBbNui25znFbRsbLTSy8eByeTcj3fhCJVuhkEJ_PeQeKtoVj8FfMBkPHbZyvKl6st8ph5jDC.OM.BDlxgHatVW8tK.usaeI3te.4wq4lo1_btIOZ7ng7gi08r9ChRa3kBzyV2XEnyxmzGSyh7A95HQzyXvZdrImbkT1lUwAIn0B56j0SjgcyzVOez6jxLIo7J1xdPHy6cUI4z2UcjKFYfvcbu3Ca5.d9.SbosWX90VTA1l7iVc1yse9zo8unxlYGEkNfzqgPS.276P_hwk.ZHZzQnZ5ruExS0OTv8B8VXIMyfNs8fN14UREjJDX7YXigfXcrhMfBDWQwhvjnhIqf6pAdywAnKT0dRanjRzPFvGdaZucwat4BPCLqoM2Ay8c6GtmA75zXyEepQba0i6x7W0lMebC46Kklr3V_yGRZpLLji3PPoWTOLsN9m9SC068iPSJQSqwMyK0HOKWN7TpRGgzZoM6YhLAXs8Ob7qr0TWEE671MK.dMtD0AMkYSntqtj_b1Wquj0mGFnUx1n96HncS9U22RMBs35CKGv8_xwFFqlycsRpikrx27uy3kWI4fT0j1BCvmA5kqvhGmYIp3f1HdoXDR_.uwFFUTDf4G3HvWbJTVKLzpEyLcItUAtaSWlLeIKjU3PZ2UHGID8JneE8B9NlUb9AsPmRDVa3ke8shrELhbkWhSJO.Mv3X3U4WkSki7kytA8jxa3idXiXAJBIMmwCv84s89qOh0XXE7VeqJGfHuT34sEDRVs4JxeIWasf6tI5zNxPT0qusm9fYeeVyGwROsJ82JB8",mdrd: "h.NGdc4sLvc4FNzpJsDW17iZtEyDwQiLNn3LP4iR4_w-1726834350-0.1.1.1",cRq: {ru: 'aHR0cHM6Ly9hcGkuaGFtc3RlcmtvbWJhdGdhbWUuaW8vaXA=',ra: 'TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDE0OyBLKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBDaHJvbWUvMTI3LjAuNjUzMy4xMDMgTW9iaWxlIFNhZmFyaS81MzcuMzY=',d: 'MuFYj12UFSOUaZcbRAsmQZn0t+iDqgDZFwcaga/9JI5RQvr6nHiKhv75/JGLbb+LvZqq91zDrK28Psov4YrZ50cz8FGFRCwL9Wb8CgVTeue7BQl2C7mYgB1F1aaqrRaIvxqWR6BvRNUK27tQioyq+zyVid1AFxKyx71xzgEYDzVQW+Lqk4IEftc8BXkOsb0EFGSIbKWmyTSGA2F4mP3pepgvlk9hcGVCchFS8YkRKisgRvHbcPpYoROW/wdHdGMzpuCcD8y3sYsOmg9Erj17lSUrWpH5I/mlfrFgvXTxZcvhnVGI96mtldX3bd2Fq8oO0u5hfr7uk19YN63434+mJeuxPLPRbnsO6VgZ6YNlY4cniQfPS0ezWc5S8y5Ni3w3qoDQdEG6ZfuIvLFGkKoR7uHF6pI2/gdapSt994jIrWW/+RkDx3KXSvIsFiEDyif+IOeAIVp7WPUAI4NgYtB1RnfIamLHLSmQedZVhxluXW8zRDnsvG+N0IF0x+YMtJ3gSUXA7FY8P/b7kTRBPSeD6Ta+0Fmnap/RZN5Jy1qVZOImNUbUr4FEE+TfpgW/92jFc1sPW9tudwlc6tnsYE92IA==',t: 'MTcyNjgzNDM1MC4wMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: 'Ns5PT7m7ihdgRwDPhQBs2Plqa1JSIUKqAsWUrwFaDEE=',i1: 'CkoCFjVrxnO9FlBI8sju4A==',i2: 'hMhDCfbpayX0PFRTfyz6sw==',zh: 'dhhwvaLkhQoQGsTRTv50LRgu00apCIBT1/RgCUZ77W0=',uh: 'YuNSku/Qc4kHTqLBV/B6FJTHluritC9yndpTv523LM8=',hh: 'LaJTt0W0XGIiEuHrUkn/U6PVoHJoBH5xlt8YAxqjVGA=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8c61b963980641a4';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/ip?__cf_chl_rt_tk=N2vkVNM7X6lfXw.qfn8knPIHbVKzDZc7kqcZ5xwNG1Q-1726834350-0.0.1.1-2600" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [ERROR] [Account 1]: ✖ Failed to get IP.
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [INFO] [Account 2]: 🌌 Starting account.
[MasterHamsterKombatBot] [2024-09-20 17:42:24] [INFO] [Account 2]: 📡 Getting account IP.
[MasterHamsterKombatBot] [2024-09-20 17:42:25] [ERROR] [Account 2]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-20 17:42:25] [ERROR] [Account 2]: ✖ Response: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "api.hamsterkombatgame.io",cType: 'managed',cNounce: '57466',cRay: '8c61b965abd28d33',cHash: 'ba9fbf5b8487f60',cUPMDTk: "\/ip?__cf_chl_tk=WtKGtMH.d2OeKGkzfSS2PfGUoIn7nhY_aN6zNt.b.oE-1726834350-0.0.1.1-2536",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '390000',cTplV: 5,cTplB: 'cf',cK: "",fa: "\/ip?__cf_chl_f_tk=WtKGtMH.d2OeKGkzfSS2PfGUoIn7nhY_aN6zNt.b.oE-1726834350-0.0.1.1-2536",md: "1vGKRqqMAhCyWH2MjIwzEC2WkATDGVa8GnMje6sVEtc-1726834350-1.1.1.1-ySR.wmPaMvimHAoMVCaUPKdbTRCffuNgHfLef68YRXriES4TW1jIuRIz3Q5WgAVrleHfBHf0PswAyQbVsb85RuF1pIZNptLc_iYJ9WfI_.VYu_yWjpUlYpqA1f4HIC2nbR7QNKKwcmdwvR6n58ye2pNThMpFiwEeOzmCon1HuXNyUDfmrE_vKSDJCGFXvvEQCaw2dRu43dIETAGlwPwsRclrSFluf9_jjaDhlwp4a4tv.OVvdxNXZkOcTnYltg3g4Uzn2DXOXG1izaQI8sKiuYnP0vWyIN47OC.FXatDwoIn1QRlBtLc2nUibjYFs7lzBVNSKCN6TPV45WaMkMqpYAR7okRhxb_ZTgRhQdU6iXbQznLwoA_j1ISPh2HarCZP5JzNsdmrs2_SYOZvcdE5WEjSxxZ4zAZs5wRxM.MZ8AfasSfyff2DH2FnQAnMkiQSV68XNC8Kbchba_l6pdks7PskTvl2tYH_tnLXlHUJP3Y4Mxdm2mYQFcZ8PXCpVeSdG_pQLHDcgcbpOQbl3eIFV1JL.2pCrgUzCf3eUm.1sRrEJGkF5wTv2YgRH5GbMZaVO6qW5y4VoFDDeDHLPW88x7KqGJF1QPrFQx03pDGtSru1njkz1wkxuO4NmcjEItgcNPkk32k5ie9Z93OHm9P1ly.d9q.SNAUv73mw043AqV.VHdjZFbvqc3KnrrEXUpX8bjRJzrfIcYVuBvSJzD_Of2N2t62V29dby3VJAvKSOKkD5nBD.Fg06iVYgy_8ML9exnk1fHXraAfA55kkvJjlITHQNLOC_iPgushQcSUUG5xdufKDbQKkHf0zaZxIxpaFYAJJSIZLdeoH68jDyuXAcH7YSdKK6AB2ZueImy82jabsiKu29XV0Ybm.vf5K3dYZqcyM0CcZlTC2yz1FCxlssMrhbaQPMInb80K625OwoEkWqq2U5jFuMhPbCo1GQmjfvtV6s.fc7_XNwqSBVbMGmIyYMuJvzAjFDBWDmagVo1J4YfagnBQoNYhkB_mRSUpXz6HM5n0ez8ejbdMl.baKQ1gbsFA4x6xBWaVD5stAMwLkTRSBLOXfmHFMDZx_eJiJQngTFw5PTJuxizOpbtbU653kUBW7JQ1pcHOzKsqJF7T0Ae3eBfFGZxbNyHb9ILYSWdQ4Q2D5Zf0aNUua9MrFq.NmU9mFrF1ut_C0QPlHymPBGdwjemc77Ce6ZebZ4j.wBFaPF6FXD5xJEcRkDnWMLz8C0nK1NOD9alD7vozuylyZH2jVSef0Ur077NKGjjLJyjGyBJcMO52XLqlIstEqdLwd2SSc0jT1XarM.oQ30651N4iaoZw2KPsQX4.Hi6prQkTdBAJlm1HIHMlFY5Z2oo3pt..T_DdeWWog83hppYUY5lgk1mBryqqlCW1LAXOmswGQ6Ztn.OL9PSy6Lp7uX9NTjpS4Ko_gx8hKEp3e5Vht.GeiPNKcoAbPZwDX_CqBNu_zQ3O9uFvRiD4EVPotiGtv_c3I2AVXA3lWPG_RUf8IMLlOGyPflTVeFL7zqe__1hlv8p4VQDukPrDz89P9vBm779.g4Oc3vsOpvPOsGVGEnHSfRuDPOgwvAXqXQWbqHQaO01Uywb0kFHYvXi5AD_pcwE7_nqEL93m0UarhgPt4wuTziI5dUOjAOEdRlxeqVt2bPkiVLHMvGFfBs.IByG_aYG7LNYMon75u9L2koE1LKDu9OEVOx9PvDMrXQ4enALtquxEDwq1YQUHL.OXQMfdtQyvvApzblsqqecslMy0v.Ojc_WWBofcJv3a2iuNzHMecI4elSn_4sc6PiJxLAEuwPm_4fLQ3q1247qSf9AwjdFCzjbkNCxmqmAbuHl3Tq0rcz3fZFVqQYjkWHJkXIc8dGOv3HdUhZ5f3nELQ4UQsXMOEIz4_hzi6b4G7suVax9Mk2ZFU0qpqAcnFjjLTDxOXFi963iwfNHOxpRZck9LeW0jfDIxmQm14JGqoxnSJd5OXvNRckrl_7NJPSUs3HBMMPq5LUj2tTZwgh5CgVn8K6oLBx3L7W48eghsWn.tRrC4k5k17cEQeMY5ky6QumBzdbAVTFZOn_2zqYGYxBGTa3RgXQli0mmxepCOmAX0HR_DuKBff5b1hDl0URfC1BJfWdvSJoefGtUuqwHXHrx5qY27U4FD89JG0XdCmtdDPb5cOYsi_mBWCB1MFHHwXkbUE9NMMm.wgueqK.3bX34qOmT_HV2h3IN.TyshLUhLoEvPwoCmgNHT6DuuacCmKGSrNEffYn6B7G5BBcc6B67P3Xwg1mwV8eBO6FXTI_sJ_H22UgpeHG4gqx3NWptNytQ9Ksyg5lLUu833MviUTU58wEwOhIjXIUga7rBuAIVa5y4RpItQWf_TwVDjoGKKZ9iYUY6EE.QC6HsGvT7Q0kBs",mdrd: "h.NGdc4sLvc4FNzpJsDW17iZtEyDwQiLNn3LP4iR4_w-1726834350-0.1.1.1",cRq: {ru: 'aHR0cHM6Ly9hcGkuaGFtc3RlcmtvbWJhdGdhbWUuaW8vaXA=',ra: 'TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDEyOyBQaXhlbCA0IFhMKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvOTQuMC40NjA2Ljg1IE1vYmlsZSBTYWZhcmkvNTM3LjM2',d: '/b1USEcThACDaokocS/SpuCU7q3YaPbvExR7EjpGGH5DPlRjDqUEZQc55WPRRn+T9esuxsUSBJ2v5otZ3W+p41miN/SY3hMi6HJ6Slnz7cZLfphpm+b1448uOTqJAjqydmhmTQI9LVtJG1eQZLYKHH/pfs4/ncvPaCHLRLoTFkYXBA7ly6JEYWLrhd/9BAlysPSZZikChkRFdEwqqCCuc8vLmYKqKM4ctz4vjfLgGBuAEEboHR/EDsy7OyJk4LF67tQK7srHHRbnTo+9SiZYRR4PFPDTXIP6QNS68s3oTAm65XXwWfyEV6SIyHAJwkwBLJt1sJ+/nQ8brUlLidpywOh9VDjz1FR6FvEh56cinwOnbRAVw+DwN5oN+3GBZoEVR5HFC6kdf3pT9NVxN3ji7/ocVsrgTIcoACDesozk8lu6zTbZHz0CsF0aET6A+lMbgAN3Bafl6CDmOHsudmIxKgoozBQgRPBvR/sGQm2anntZoXzKznOLH352ZzDNuEfxs7rlLhelpIJrwDbYCDH4ixKEOkFU2e8rU4SbxsVLztqlovIM1z5PqS8pjsDPvdSTbfcx+k5u3Yxw//MeS3oR9g==',t: 'MTcyNjgzNDM1MC4wMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: 'rxTiwv+0LJET8zQy/UC14oCGu1qykkIdQt53fB0Waxo=',i1: 'xDFLeKY6HCSn+BvOQZfW2w==',i2: 'Q3JHyb3OpovSiAoJUePm7w==',zh: 'dhhwvaLkhQoQGsTRTv50LRgu00apCIBT1/RgCUZ77W0=',uh: 'FcuDpLqnzGEIZmgxyl8lbodnRB/FXpus9lzvjoES32o=',hh: 'LaJTt0W0XGIiEuHrUkn/U6PVoHJoBH5xlt8YAxqjVGA=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8c61b965abd28d33';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/ip?__cf_chl_rt_tk=WtKGtMH.d2OeKGkzfSS2PfGUoIn7nhY_aN6zNt.b.oE-1726834350-0.0.1.1-2536" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
[MasterHamsterKombatBot] [2024-09-20 17:42:25] [ERROR] [Account 2]: ✖ Failed to get IP.
[MasterHamsterKombatBot] [2024-09-20 17:42:25] [WARNING]  😴 Sleeping for 30 seconds because of random delay.
[MasterHamsterKombatBot] [2024-09-20 17:42:34] [ERROR] Bot Stop by user!

**Comment by copycatcodex** [comment]
I also experienced it earlier and it was indeed an error from the server, it's almost like that often.
and it's not a problem with the bot

**Comment by ZProtons** [comment]
are you sure. cuz now it says, not found
 ===============[ STARTING ALL ACCOUNTS ]===============
[MasterHamsterKombatBot] [2024-09-20 18:37:12] [INFO] [Account 1]: 🌌 Starting account.
[MasterHamsterKombatBot] [2024-09-20 18:37:12] [INFO] [Account 1]: 📡 Getting account IP.
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 1]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 1]: ✖ Response: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 1]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 1]: ✖ Response: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>







[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 1]: ✖ Failed to get IP.
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [INFO] [Account 2]: 🌌 Starting account.
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [INFO] [Account 2]: 📡 Getting account IP.
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 2]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 2]: ✖ Response: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 2]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 2]: ✖ Response: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>







[MasterHamsterKombatBot] [2024-09-20 18:37:13] [ERROR] [Account 2]: ✖ Failed to get IP.
[MasterHamsterKombatBot] [2024-09-20 18:37:13] [WARNING]  😴 Sleeping for 40 seconds because of random delay.
