### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#486]
![image](https://github.com/user-attachments/assets/c6512708-6c73-467f-b0a7-027699d628d9)

**Comment by Ashwin3454** [comment]
I recieved the same error. but hamster working fine in mobile

**Comment by Zhangxiaokang123** [comment]
> Don't worry, I recieved the same error. its a maintenance break
> 
> <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/180084972/369418137-737c86af-7b70-434e-b82e-bf414697366e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDIzMTQsIm5iZiI6MTcyNjg0MjAxNCwicGF0aCI6Ii8xODAwODQ5NzIvMzY5NDE4MTM3LTczN2M4NmFmLTdiNzAtNDM0ZS1iODJlLWJmNDE0Njk3MzY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNDIwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWM3MDAyZjM5NzU4ZGQ4Y2M3MTg5ZmE5OThmZGJiMTBjYmVkZDk2MTNjMWRmZDQ5MGVkMDY2MGY2MmJmZWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HMCU0L0SMwLHkLQSGOa1CfU57YQ286-N8Z2fPrfYjVI">

me too

**Comment by Microzibert** [comment]
I launched the bot in the Windows 10 terminal and everything worked. Although at the same time nothing worked on Linux

**Comment by Fy0urM** [comment]
this is not an operating system problem, `404 is page not found`, `500 internal server error`, happens when developers break something with the next update, `<title>Just a moment...</title>` this is most likely triggered by cloudflare bot check.

**Comment by QualityRU** [comment]
it works

**Comment by Fy0urM** [comment]
yes, the bot is working now, sometimes it gives 1-2 errors, but it is much more stable now than it was a few hours ago
