### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by byanonim** [masterking32/MasterHamsterKombatBot#49]
proxy not working. I tried both http and https, but the IP is my ISP's IP.

![proxy](https://github.com/user-attachments/assets/ecb46b9d-f7af-46be-8cd8-be16c8093bb5)

**Comment by masterking32** [comment]
Check this:
https://github.com/masterking32/MasterHamsterKombatBot/discussions/39

**Comment by byanonim** [comment]
Can i use socks protocol?
