### ISSUE TITLE
Cheated accounts will not get the airdrop on Season 1

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterHamsterKombatBot#490]
what's the meaning of it? If I had cheated, they would have blocked my account so I wouldn't waste your time. I've for morethan 3 months, now they're saying the airdrop isn't applicable? I swear, Hamster team is really bad!

<img width="959" alt="image" src="https://github.com/user-attachments/assets/0e739859-335a-4371-88e1-4515a6dc637d">

**Comment by yanpaing007** [comment]
Opps...

**Comment by yanpaing007** [comment]
Btw where did you get this information from ,can you share it?

**Comment by vashamamasha2014** [comment]
![image](https://github.com/user-attachments/assets/030a4885-c462-49aa-87ba-9d3097a419b4) all accounts...

**Comment by MeninSun** [comment]
> Sad Life
> 
> <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/180084972/369526437-0e739859-335a-4371-88e1-4515a6dc637d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjAwNzUsIm5iZiI6MTcyNjg1OTc3NSwicGF0aCI6Ii8xODAwODQ5NzIvMzY5NTI2NDM3LTBlNzM5ODU5LTMzNWEtNDM3MS04OGUxLTQ1MTVhNmRjNjM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxOTE2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTBlZWJmOWIxZmU4ZWRjODQwNTcyY2RkNTdkOTY4NTczOTIzYTQzMmYzZGUxYjg2ZWRhZmNiZmY2MmU5N2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IufISnEVD9RW1XzXu6avJQrayfGnegXJoRyxN2VVJvw">

Cry baby cry
![Screenshot_20240921_013442](https://github.com/user-attachments/assets/205c308e-1acb-4b8d-b42f-67c4889a3467)

**Comment by autoattack999** [comment]
I have a lot of accounts but not all of them are banned, it's strange, but most of them are banned, only a few are not banned.
