### ISSUE TITLE
Big Update

### ISSUE THREAD

**Issue by Mihaitafox11** [masterking32/MasterHamsterKombatBot#491]
They changed the system to diamonds, can you do your magic sir?

**Comment by Pawansingh333** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot?tab=readme-ov-file#-hamster-kombat-s1-has-been-finished
