### ISSUE TITLE
Update is already in the game

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#492]
Season two is already in the game. A little about the changes
1) coins have been replaced with crystals
2) all progress has been reset
3) the friends list has been hidden
4) playground games remain in the game
5) buying cards is now in the playground section as well as the mini game.

Basically, nothing has changed, only the graphic design has changed a little

![IMG_20240920_221420](https://github.com/user-attachments/assets/5869f7d8-2605-40ab-a97d-390f154b6089)

**Comment by Zhangxiaokang123** [comment]
> Season two is already in the game. A little about the changes
> 
> 1. coins have been replaced with crystals
> 2. all progress has been reset
> 3. the friends list has been hidden
> 4. playground games remain in the game
> 5. buying cards is now in the playground section as well as the mini game.
> 
> Basically, nothing has changed, only the graphic design has changed a little
> 
> ![IMG_20240920_221420](https://private-user-images.githubusercontent.com/175958587/369530256-5869f7d8-2605-40ab-a97d-390f154b6089.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Nzg2MjksIm5iZiI6MTcyNjg3ODMyOSwicGF0aCI6Ii8xNzU5NTg1ODcvMzY5NTMwMjU2LTU4NjlmN2Q4LTI2MDUtNDBhYi1hOTdkLTM5MGYxNTRiNjA4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwMDI1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzc1YTEzM2ZkMDQ4M2UyMzM1YTIxYjllODdiMGY5NWUyNmQ3NjgxMDEzMDhhODczYzJkNmZjODM4MmNmNWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yMeSlAH4ER0S0Y6zf4nvKMKI5ZEFliUsD6iK5SRUnI8)

Diamonds seem to only be available for games and tasks, Click to get diamonds doesn't seem to be turned on.
