### ISSUE TITLE
Status code is not 200

### ISSUE THREAD

**Issue by h0kum** [masterking32/MasterHamsterKombatBot#494]
Hi, 
after finish S1
when running the script, a message comes up:

[MasterHamsterKombatBot] [2024-09-21 08:40:21] [ERROR] [h__m]: ✖ Status code is not 200
[MasterHamsterKombatBot] [2024-09-21 08:40:21] [ERROR] [h__m]: ✖ Response: NOT_FOUND
[MasterHamsterKombatBot] [2024-09-21 08:40:21] [ERROR] [h__m]: 🌐 Unable to get account data.

how to fix?

**Comment by Ashwin3454** [comment]
Script not updated. Wait for update
