### ISSUE TITLE
Error use proxy

### ISSUE THREAD

**Issue by oboroccv** [masterking32/MasterHamsterKombatBot#53]
![1](https://github.com/user-attachments/assets/2b9254ba-37ca-48ec-b324-b419caa9e912)
![2](https://github.com/user-attachments/assets/b8edaf76-4ec2-4c0b-a67f-92a7e6cd149d)

**Comment by AlexArGC** [comment]
No type!
"https" : "proxy string"

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/39
