### ISSUE TITLE
Проблема при Cooldown

### ISSUE THREAD

**Issue by pashva11** [masterking32/MasterHamsterKombatBot#58]
Привет!
Проблема возникает не всегда, но периодически и только когда карточки находятся в режиме Cooldown.

![баг ХК](https://github.com/user-attachments/assets/6c72a897-4d14-44d0-8f42-72d2f65207d4)

**Comment by cmeept** [comment]
MaxRandomDelay и AccountsRecheckTime удлини и может выручит . У тебя наверно 0 стоит ? Надеюсь помог .

**Comment by pashva11** [comment]
> MaxRandomDelay и AccountsRecheckTime удлини и может выручит . У тебя наверно 0 стоит ? Надеюсь помог .

Нет - у меня 120 и 300 секунд эти показатели. Может есть ещё идеи?

**Comment by masterking32** [comment]
Try with the last version.

**Comment by Kolesnikov-R** [comment]
Latest version 
![Снимок экрана от 2024-07-23 19-31-20](https://github.com/user-attachments/assets/ad72b3c9-8e4d-48ce-8dd2-b1a34be91690)

**Comment by masterking32** [comment]
try this.
https://github.com/masterking32/MasterHamsterKombatBot/blob/main/utilities.py

**Comment by Kolesnikov-R** [comment]
> попробуйте это. https://github.com/masterking32/MasterHamsterKombatBot/blob/main/utilities.py

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Hamster\main-0619.py", line 1170, in <module>
    main()
  File "C:\Users\User\Desktop\Hamster\main-0619.py", line 1164, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Hamster\main-0619.py", line 1131, in RunAccounts
    account.Start()
  File "C:\Users\User\Desktop\Hamster\main-0619.py", line 1031, in Start
    if not self.BuyBestCard():
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Hamster\main-0619.py", line 657, in BuyBestCard
    if best_next_card is not None and self.balanceCoins > best_next_card["price"]:
                                                          ~~~~~~~~~~~~~~^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str

**Comment by Kolesnikov-R** [comment]
ChatGPT указывает следующее:
В данном случае проблема возникает в следующем фрагменте кода:
if best_next_card is not None and self.balanceCoins > best_next_card["price"]:
Эта ошибка может возникнуть по нескольким причинам:

best_next_card является кортежем, а не словарем: Ваша функция BuyBestCard возвращает кортеж, а не словарь, или где-то в коде переменная best_next_card переписывается на кортеж.
Чтобы исправить эту ошибку, выполните следующие шаги:

1. Проверьте функцию BuyBestCard
Убедитесь, что функция BuyBestCard возвращает правильный тип данных. Она должна возвращать словарь, а не кортеж. Проверьте её реализацию и убедитесь, что она возвращает словарь с ключом 'price'.

Вот пример проверки функции:
def BuyBestCard(self):
    # Предполагается, что функция возвращает словарь
    best_next_card = ...  # логика для выбора лучшей карты

    if isinstance(best_next_card, dict):
        if 'price' in best_next_card:
            # Используйте best_next_card как словарь
            return best_next_card
        else:
            log.error(f"Лучшее следующее улучшение не содержит ключ 'price': {best_next_card}")
            return None
    else:
        log.error(f"Лучшее следующее улучшение возвращает неправильный тип: {type(best_next_card)}")
        return None

2. Проверьте вызовы функции BuyBestCard
Проверьте, как вы вызываете функцию BuyBestCard и как она используется:

best_next_card = self.BuyBestCard()
if best_next_card is not None and isinstance(best_next_card, dict):
    if self.balanceCoins > best_next_card["price"]:
        # Дальнейшая обработка

3. Убедитесь, что везде используются правильные типы данных
Если в других частях кода вы также обрабатываете данные, которые должны быть словарями, убедитесь, что они действительно являются словарями, а не кортежами.

После внесения изменений и проверок, ошибка TypeError должна быть устранена.


Что Вы думаете ?

**Comment by pashva11** [comment]
> Попробуйте использовать последнюю версию.

Загрузил последнюю версию, но к сожалению, ошибка продолжает появляться
![Clip2net_240723234125](https://github.com/user-attachments/assets/bae6f9db-fda9-4269-bf46-df0c5d8cf9e9)

**Comment by Kolesnikov-R** [comment]
> try this. https://github.com/masterking32/MasterHamsterKombatBot/blob/main/utilities.py

Я нашёл ошибку в вашем скрипте. 

Если использовать Telegram Bot, ошибка появляется, и скрипт останавливается. 

Однако, если отключить использование Telegram Bot, ошибка не появляется, и скрипт работает долгое время. На данный момент непрерывная работа составляет 60 минут, и скрипт не останавливается. 

У вас есть идея, как эту ошибку можно исправить? 

Спасибо!

=In English. =

I found an error in your script.

When using the Telegram Bot, an error occurs, and the script stops.

However, if the use of the Telegram Bot is disabled, the error does not occur, and the script runs for a long time. Currently, it has been running continuously for 60 minutes without stopping.

Do you have any ideas on how to fix this error?

Thank you!

**Comment by pashva11** [comment]
> > Попробуйте использовать последнюю версию.
> 
> Загрузил последнюю версию, но к сожалению, ошибка продолжает появляться ![Clip2net_240723234125](https://private-user-images.githubusercontent.com/175673781/351500785-bae6f9db-fda9-4269-bf46-df0c5d8cf9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NzQ1MTEsIm5iZiI6MTcyMTc3NDIxMSwicGF0aCI6Ii8xNzU2NzM3ODEvMzUxNTAwNzg1LWJhZTZmOWRiLWZkYTktNDI2OS1iZjQ2LWRmMGM1ZDhjZjllOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QyMjM2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTU3ZTdiNDY2MTNlZjg3MTYzM2NiZWExZGY2MWNkMDNiYjJlZDFmMjRlN2VjMGMwZDgxZDJhODY0OWUzMDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vbSTzCfGpT3HQn5-bI5FxSvIM1hGnPEgnvja2mKMAus)

После того, как я обновил и файл utilities и файл main  - тогда ошибка исчезла! Спасибо за вашу работу. (если появится ошибка - тогда ещё напишу)

**Comment by masterking32** [comment]
Now try the last version and give me feedback.

**Comment by pashva11** [comment]
Работает всё отлично! У меня не возникло ни одной ошибки! Супер!!!

**Comment by masterking32** [comment]
> > Now try the last version and give me feedback.
> 
> Hello!
> 
> Thank you very much, my friend! I have updated to the latest version and have no issues. I have a question: have I understood correctly that thanks to your bot, I no longer need to keep the phone screen on? The coins will continuously accumulate as long as this script is running?
> 
> Thank you!

Hello, yes, so turn your phone screen off.
I'm gonna close this.
