### ISSUE TITLE
An idea on how to implement an automatic puzzle solution

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#60]
The puzzle is not random.  It is updated once at a certain time, and the solution is provided on the official YouTube channel.  _(I’m not an IT specialist)_ Is it possible to add a prepared sequence of actions from a video to the code, and then the bot will simply reproduce these actions on all accounts.

`https://youtu.be/rqFkVwfzfkI?si=i_3c1_KdpdtYvcEO`
`Time code: 1:35`

**Comment by pashva11** [comment]
Этот бот уже умеет решать головоломку и получать ключ. Других решений, на сколько я понимаю, сейчас не нужно. Благодарим за вашу идею!

**Comment by masterking32** [comment]
This feature already exists.
