### ISSUE TITLE
Please 

### ISSUE THREAD

**Issue by Pawansingh333** [masterking32/MasterHamsterKombatBot#65]
Can you write the code so that it automatically reads account name, Authorization, UserAgent, and Proxy from a .env or .csv file? This means we can list multiple account names, Authorization, UserAgent, and Proxy in a .csv or .env file, and the code will read and run with those details automatically

**Comment by AlexArGC** [comment]
What for? This desire is your whim. Who needs such a parser? Go to the exchange and buy a coder or write it yourself.

**Comment by pashva11** [comment]
> Зачем? Это желание - ваша прихоть. Кому нужен такой парсер? Идите на биржу и купите верстальщик или напишите его сами. Было бы лучше задать вопрос в обсуждении, но здесь речь идет об ошибках.

Это нужно, чтобы не переносить все данные обо всех аккаунтах каждый раз, когда изменяется файл main.py - это не прихоть, а разумное улучшение.

**Comment by Pawansingh333** [comment]
> Refere

sorry but im just requesting

**Comment by AlexArGC** [comment]
> Это нужно, чтобы не переносить все данные обо всех аккаунтах каждый раз, когда изменяется файл main.py - это не прихоть, а разумное улучшение.

Account setup has nested dictionaries. The output is a very long CSV. Inconvenient!? The simplest solution is to throw the AccountList into a separate file `config.py` and load it via import to main `from config import *`. And you will be happy!

``

**Comment by pashva11** [comment]
Да, возможно... Только я плохо понимаю в программировании, к сожалению... Вот если бы это сделал автор бота и дальше во всех версиях поддерживал - было бы здорово!
