### ISSUE TITLE
bug: Max retries exceeded with url:

### ISSUE THREAD

**Issue by AlexArGC** [masterking32/MasterHamsterKombatBot#68]
I get this error from time to time.

`Error: HTTPSConnectionPool(host='api.hamsterkombatgame.io', port=443): Max retries exceeded with url: /clicker/boosts-for-buy (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002A142C95AF0>, 'Connection to api.hamsterkombatgame.io timed out. (connect timeout=None)'))`

Added data type checking and a delay after an invalid request of 5 seconds.
```
        except Exception as e:
            log.error(f"[{self.account_name}] Error: {e}")
            self.SendTelegramLog(f"[{self.account_name}] Error: {e}", "http_errors")
            time.sleep(5)
            return False
```
Does not help.

**Comment by pashva11** [comment]
У меня тоже иногда появляется эта ошибка...

**Comment by masterking32** [comment]
Connection Error!
