### ISSUE TITLE
Daily combo

### ISSUE THREAD

**Issue by akumanomi1988** [masterking32/MasterHamsterKombatBot#69]
Would it be possible to purchase the daily combo considering the necessary cards for it, or if referrals are needed, to do something about it?

**Comment by odysahe** [comment]
> Would it be possible to purchase the daily combo considering the necessary cards for it, or if referrals are needed, to do something about it?

I hope so too 🥹

**Comment by paisekamao** [comment]
is this possible to add feature of daily combo????

**Comment by SanaurAsif** [comment]
It seems that adding a daily combo feature might not be feasible because the API doesn't provide the names of the combo cards. It only indicates whether a card is part of the daily combo when the card is purchased or upgraded.

**Comment by l0v3m0n3y** [comment]
Solved this problem with the help of 
data=requests.post("https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]
for i in data:
i=i["card_name"]
It works well

**Comment by joshuazzz1** [comment]
> Solved this problem with the help of data=requests.post("[https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]](https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list%22,json=%7B%7D).json()%5B%22data%22%5D%5B%22dailyComboCards%22%5D) for i in data: i=i["card_name"] It works well

In which line to add that code?

**Comment by l0v3m0n3y** [comment]
> > Solved this problem with the help of data=requests.post("[https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]](https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list%22,json=%7B%7D).json()%5B%22data%22%5D%5B%22dailyComboCards%22%5D) for i in data: i=i["card_name"] It works well
> 
> In which line to add that code?

This function gives the name of the combo cards to buy. I designed it in my script like this
![Screenshot_2024-08-15-20-25-58-332](https://github.com/user-attachments/assets/afebe97f-c430-4e00-ba7a-e34f11bfd282)

**Comment by D41214N** [comment]
> > > Solved this problem with the help of data=requests.post("[https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]](https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list%22,json=%7B%7D).json()%5B%22data%22%5D%5B%22dailyComboCards%22%5D) for i in data: i=i["card_name"] It works well
> > 
> > 
> > In which line to add that code?
> 
> This function gives the name of the combo cards to buy. I designed it in my script like this
Hey
While this works well, I understand that hamstercombos.com isn't the official API and there might be a delay in the data. Could you please explain how and where the official data for these combo cards is obtained? Specifically, I'd like to know:

What API calls to the official Hamster Kombat API (api.hamsterkombatgame.io) are used to source this data?
How the data is processed or transformed before it’s made available at hamstercombos.com?
Is there any way to directly access this data from the official API to avoid delays?

**Comment by ParsapythonLv** [comment]
really need add this future

**Comment by tboy1337** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/304

**Comment by ParsapythonLv** [comment]
It has been some time since one of my friends requested that card combos should be purchased every day according to the ratio of their income to their cost, and this is really needed, and maybe the amount of their income is sometimes not high, but we will receive a good profit, which is before buying cards. Profit should take priority with the combo so that all the money is not spent and he can buy Haru cards, also considering that this robot has this capability in it, you can get help from it (written with a translator)❤️
https://github.com/shamhi/HamsterKombatBot

**Comment by MixxxGit** [comment]
> > > Решил эту проблему с помощью data=requests.post(" [ https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data" ]["dailyComboCards"] ](https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list%22,json=%7B%7D) .json()%5B%22data%22%5D%5B%22dailyComboCards%22%5D) для i в данных: i=i["card_name"] Это работает хорошо
> > 
> > 
> > В какую строку добавить этот код?
> 
> Эта функция дает название комбо-карт, которые можно купить. Я разработал это в своем сценарии следующим образом ![Скриншот_2024-08-15-20-25-58-332](https://private-user-images.githubusercontent.com/94906343/358325552-afebe97f-c430-4e00-ba7a-e34f11bfd282.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTg5NjcsIm5iZiI6MTcyNTYxODY2NywicGF0aCI6Ii85NDkwNjM0My8zNTgzMjU1NTItYWZlYmU5N2YtYzQzMC00ZTAwLWJhN2EtZTM0ZjExYmZkMjgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEwMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZjIxZDgzYmY5ODIxOWU1ZTExNmMxYzU1YTBhZDUwMTI4Y2I0MmEyYzQ0N2RjMWU4NjlkZDQ5N2FlYTc4NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XX2TY5sV5wD6Puz2lRTnCwRDPkytUmRHAH1EjvgPBYI)
It’s amazing that this works for you because you use the card name as if it were its ID, but it’s not. For example Name = "Data Center Tokyo" ID = "data_center_tokyo"

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/commit/a6fd7d1175707e1333b8a969ad9112e7a47de642
