### ISSUE TITLE
KeyError: 'auto_playground_games'

### ISSUE THREAD

**Issue by yb2222688** [masterking32/MasterHamsterKombatBot#91]
Hi. Thanks a lot for this script! it's the best. but here I have this problem after 29 July update. Can you please tell me what is the error ?

ps i'm using the older version for now

KeyError: 'auto_playground_games'

Thank you for your time

<img width="1102" alt="Снимок экрана 2024-08-01 в 20 29 21" src="https://github.com/user-attachments/assets/07488281-83cd-4a45-a066-eb8a238edb8c">

**Comment by masterking32** [comment]
Need to update configs too, `auto_playground_games` is not exists in your config.
