### ISSUE TITLE
Bug in"wait_for_best_card" 

### ISSUE THREAD

**Issue by topcj** [masterking32/MasterHamsterKombatBot#93]
Hello boy
Thank you for your development and support
When I enable "wait_for_best_card" the bot stops and I can't use this nice feature.
This bug is not seen when "enable_parallel_upgrades" is disabled.

Why does this happen?
@masterking32

_> [Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] Welcome to [Master Hamster Kombat] Auto farming bot...
[Master HamsterKombat Bot][INFO] Project Github: https://github.com/masterking32/MasterHamsterKombatBot
[Master HamsterKombat Bot][INFO] Developed by: MasterkinG32
[Master HamsterKombat Bot][INFO] Version: 2.20
[Master HamsterKombat Bot][INFO] To stop the bot, press Ctrl + C
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] Starting all accounts...
[Master HamsterKombat Bot][INFO] [acc1] Starting account...
[Master HamsterKombat Bot][INFO] [acc1] Getting basic account data...
[Master HamsterKombat Bot][INFO] [acc1] Account ID: xxxxxxxx, Account detected as bot: False
[Master HamsterKombat Bot][INFO] [acc1] Getting account config data...
[Master HamsterKombat Bot][INFO] [acc1] Getting account data...
[Master HamsterKombat Bot][INFO] [acc1] Account Balance Coins: 605.83m, Available Taps: 1347, Max Taps: 10500, Total Keys: 29, Balance Keys: 29
[Master HamsterKombat Bot][INFO] [acc1] Getting account upgrades...
[Master HamsterKombat Bot][INFO] [acc1] Getting account tasks...
[Master HamsterKombat Bot][INFO] [acc1] Getting account airdrop tasks...
[Master HamsterKombat Bot][INFO] [acc1] Getting account IP...
[Master HamsterKombat Bot][INFO] [acc1] IP: ------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] [acc1] Playground games are disabled.
[Master HamsterKombat Bot][INFO] [acc1] Checking for best card...
[Master HamsterKombat Bot][INFO] [acc1] Searching for the best upgrades...
[Master HamsterKombat Bot][WARNING] [acc1] Market Making is on cooldown, Checking for next card...
[Master HamsterKombat Bot][WARNING] [acc1] Sport Collectibles Marketplace is on cooldown, Checking for next card...
[Master HamsterKombat Bot][WARNING] [acc1] This is fine is on cooldown, Checking for next card...
[Master HamsterKombat Bot][WARNING] [acc1] Crypto Farming is on cooldown, Checking for next card...
Traceback (most recent call last):
  File "E:\main.py", line 1412, in <module>
    main()
  File "E:\main.py", line 1406, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "E:\main.py", line 1373, in RunAccounts
    account.Start()
  File "E:\main.py", line 1273, in Start
    if not self.BuyBestCard():
           ^^^^^^^^^^^^^^^^^^
  File "E:\main.py", line 652, in BuyBestCard
    CalculateCardProfitCoefficient(selected_card)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'CalculateCardProfitCoefficient' is not defined_

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/issues/90

**Comment by topcj** [comment]
I updated, it stops again.
